// Generated by scripts/build-content.mjs — do not edit by hand.
// Source: content/lessons/*.md

import type { LessonDay } from '@/types';

export const day24: LessonDay = {
  day: 24,
  title: "Nederland en Portugal vergelijken",
  goal: "eenvoudige verschillen tussen landen, steden en leefstijlen uitleggen.",
  checkpoint: false,
  modules: [
    {
      id: "d24-vocabulary",
      lessonDay: 24,
      type: "vocabulary",
      estimatedMinutes: 8,
      items: [
        { id: "w-mais", type: "word", portuguese: "mais", dutch: "meer", dayIntroduced: 4, category: "in-een-cafe-bestellen", priority: 1 },
        { id: "w-menos", type: "word", portuguese: "menos", dutch: "minder", dayIntroduced: 24, category: "nederland-en-portugal-vergelijken", priority: 1 },
        { id: "w-melhor", type: "word", portuguese: "melhor", dutch: "beter", dayIntroduced: 24, category: "nederland-en-portugal-vergelijken", priority: 1 },
        { id: "w-pior", type: "word", portuguese: "pior", dutch: "slechter", dayIntroduced: 24, category: "nederland-en-portugal-vergelijken", priority: 1 },
        { id: "w-maior", type: "word", portuguese: "maior", dutch: "groter", dayIntroduced: 24, category: "nederland-en-portugal-vergelijken", priority: 1 },
        { id: "w-menor", type: "word", portuguese: "menor", dutch: "kleiner", dayIntroduced: 24, category: "nederland-en-portugal-vergelijken", priority: 1 },
        { id: "w-caro", type: "word", portuguese: "caro", dutch: "duur", dayIntroduced: 12, category: "winkelen", priority: 1 },
        { id: "w-barato", type: "word", portuguese: "barato", dutch: "goedkoop", dayIntroduced: 12, category: "winkelen", priority: 1 },
        { id: "w-quente", type: "word", portuguese: "quente", dutch: "warm", dayIntroduced: 24, category: "nederland-en-portugal-vergelijken", priority: 1 },
        { id: "w-frio", type: "word", portuguese: "frio", dutch: "koud", dayIntroduced: 3, category: "hoe-gaat-het", priority: 1 },
        { id: "w-tranquilo", type: "word", portuguese: "tranquilo", dutch: "rustig", dayIntroduced: 3, category: "hoe-gaat-het", priority: 1 },
        { id: "w-movimentado", type: "word", portuguese: "movimentado", dutch: "levendig / druk", dayIntroduced: 24, category: "nederland-en-portugal-vergelijken", priority: 1 },
        { id: "w-diferente", type: "word", portuguese: "diferente", dutch: "verschillend", dayIntroduced: 24, category: "nederland-en-portugal-vergelijken", priority: 1 },
        { id: "w-parecido", type: "word", portuguese: "parecido", dutch: "vergelijkbaar", dayIntroduced: 24, category: "nederland-en-portugal-vergelijken", priority: 1 },
        { id: "w-clima", type: "word", portuguese: "clima", dutch: "klimaat", dayIntroduced: 24, category: "nederland-en-portugal-vergelijken", priority: 1 },
      ],
    },
    {
      id: "d24-chunks",
      lessonDay: 24,
      type: "chunks",
      estimatedMinutes: 7,
      items: [
        { id: "c-portugal-e-mais-quente", type: "chunk", portuguese: "Portugal é mais quente.", dutch: "Portugal is warmer.", dayIntroduced: 24, category: "nederland-en-portugal-vergelijken", priority: 2 },
        { id: "c-os-paises-baixos-sao-mais-pequenos", type: "chunk", portuguese: "Os Países Baixos são mais pequenos.", dutch: "Nederland is kleiner.", dayIntroduced: 24, category: "nederland-en-portugal-vergelijken", priority: 2 },
        { id: "c-aqui-e-mais-tranquilo", type: "chunk", portuguese: "Aqui é mais tranquilo.", dutch: "Hier is het rustiger.", dayIntroduced: 24, category: "nederland-en-portugal-vergelijken", priority: 2 },
        { id: "c-e-muito-diferente", type: "chunk", portuguese: "É muito diferente.", dutch: "Het is heel anders.", dayIntroduced: 24, category: "nederland-en-portugal-vergelijken", priority: 2 },
        { id: "c-e-parecido-com", type: "chunk", portuguese: "É parecido com…", dutch: "Het lijkt op…", dayIntroduced: 24, category: "nederland-en-portugal-vergelijken", priority: 2 },
        { id: "c-gosto-mais-de", type: "chunk", portuguese: "Gosto mais de…", dutch: "Ik hou meer van…", dayIntroduced: 24, category: "nederland-en-portugal-vergelijken", priority: 2 },
        { id: "c-para-mim-e-melhor", type: "chunk", portuguese: "Para mim, é melhor.", dutch: "Voor mij is het beter.", dayIntroduced: 24, category: "nederland-en-portugal-vergelijken", priority: 2 },
        { id: "c-depende-da-situacao", type: "chunk", portuguese: "Depende da situação.", dutch: "Het hangt van de situatie af.", dayIntroduced: 24, category: "nederland-en-portugal-vergelijken", priority: 2 },
      ],
    },
    {
      id: "d24-grammar",
      lessonDay: 24,
      type: "grammar",
      estimatedMinutes: 5,
      items: [],
      notes: [
        {
          title: "Grammatica",
          body: [],
          points: ["mais … do que — meer … dan","menos … do que — minder … dan","melhor — beter","pior — slechter"],
        },
      ],
    },
    {
      id: "d24-speaking",
      lessonDay: 24,
      type: "speaking",
      estimatedMinutes: 15,
      items: [],
      tasks: [
        {
          title: "Spreekopdracht",
          kind: "speaking",
          body: ["Vergelijk Nederland en Portugal op minimaal vier punten."],
          steps: [],
        },
      ],
    },
  ],
};
