// Generated by scripts/build-content.mjs — do not edit by hand.
// Source: content/lessons/*.md

import type { LessonDay } from '@/types';

export const day01: LessonDay = {
  day: 1,
  title: "Begroeten & jezelf voorstellen",
  goal: "iemand begroeten en in 30–60 seconden vertellen wie je bent.",
  checkpoint: false,
  modules: [
    {
      id: "d01-vocabulary",
      lessonDay: 1,
      type: "vocabulary",
      estimatedMinutes: 8,
      items: [
        { id: "w-ola", type: "word", portuguese: "olá", dutch: "hallo", dayIntroduced: 1, category: "begroeten-jezelf-voorstellen", priority: 1 },
        { id: "w-bom-dia", type: "word", portuguese: "bom dia", dutch: "goedemorgen", dayIntroduced: 1, category: "begroeten-jezelf-voorstellen", priority: 1 },
        { id: "w-boa-tarde", type: "word", portuguese: "boa tarde", dutch: "goedemiddag", dayIntroduced: 1, category: "begroeten-jezelf-voorstellen", priority: 1 },
        { id: "w-boa-noite", type: "word", portuguese: "boa noite", dutch: "goedenavond / goedenacht", dayIntroduced: 1, category: "begroeten-jezelf-voorstellen", priority: 1 },
        { id: "w-ate-logo", type: "word", portuguese: "até logo", dutch: "tot later", dayIntroduced: 1, category: "begroeten-jezelf-voorstellen", priority: 1 },
        { id: "w-adeus", type: "word", portuguese: "adeus", dutch: "dag / vaarwel", dayIntroduced: 1, category: "begroeten-jezelf-voorstellen", priority: 1 },
        { id: "w-obrigado", type: "word", portuguese: "obrigado", dutch: "bedankt", dayIntroduced: 1, category: "begroeten-jezelf-voorstellen", priority: 1 },
        { id: "w-por-favor", type: "word", portuguese: "por favor", dutch: "alstublieft", dayIntroduced: 1, category: "begroeten-jezelf-voorstellen", priority: 1 },
        { id: "w-sim", type: "word", portuguese: "sim", dutch: "ja", dayIntroduced: 1, category: "begroeten-jezelf-voorstellen", priority: 1 },
        { id: "w-nao", type: "word", portuguese: "não", dutch: "nee / niet", dayIntroduced: 1, category: "begroeten-jezelf-voorstellen", priority: 1 },
        { id: "w-eu", type: "word", portuguese: "eu", dutch: "ik", dayIntroduced: 1, category: "begroeten-jezelf-voorstellen", priority: 1 },
        { id: "w-tu", type: "word", portuguese: "tu", dutch: "jij", dayIntroduced: 1, category: "begroeten-jezelf-voorstellen", priority: 1 },
        { id: "w-ser", type: "word", portuguese: "ser", dutch: "zijn", dayIntroduced: 1, category: "begroeten-jezelf-voorstellen", priority: 1 },
        { id: "w-chamar-se", type: "word", portuguese: "chamar-se", dutch: "heten", dayIntroduced: 1, category: "begroeten-jezelf-voorstellen", priority: 1 },
        { id: "w-portugues", type: "word", portuguese: "português", dutch: "Portugees", dayIntroduced: 1, category: "begroeten-jezelf-voorstellen", priority: 1 },
      ],
    },
    {
      id: "d01-chunks",
      lessonDay: 1,
      type: "chunks",
      estimatedMinutes: 7,
      items: [
        { id: "c-ola-bom-dia", type: "chunk", portuguese: "Olá, bom dia.", dutch: "Hallo, goedemorgen.", dayIntroduced: 1, category: "begroeten-jezelf-voorstellen", priority: 2 },
        { id: "c-como-te-chamas", type: "chunk", portuguese: "Como te chamas?", dutch: "Hoe heet je?", dayIntroduced: 1, category: "begroeten-jezelf-voorstellen", priority: 2 },
        { id: "c-chamo-me-duran", type: "chunk", portuguese: "Chamo-me Duran.", dutch: "Ik heet Duran.", dayIntroduced: 1, category: "begroeten-jezelf-voorstellen", priority: 2 },
        { id: "c-sou-neerlandes", type: "chunk", portuguese: "Sou neerlandês.", dutch: "Ik ben Nederlands.", dayIntroduced: 1, category: "begroeten-jezelf-voorstellen", priority: 2 },
        { id: "c-sou-dos-paises-baixos", type: "chunk", portuguese: "Sou dos Países Baixos.", dutch: "Ik kom uit Nederland.", dayIntroduced: 1, category: "begroeten-jezelf-voorstellen", priority: 2 },
        { id: "c-estou-a-aprender-portugues", type: "chunk", portuguese: "Estou a aprender português.", dutch: "Ik ben Portugees aan het leren.", dayIntroduced: 1, category: "begroeten-jezelf-voorstellen", priority: 2 },
        { id: "c-falo-um-pouco-de-portugues", type: "chunk", portuguese: "Falo um pouco de português.", dutch: "Ik spreek een beetje Portugees.", dayIntroduced: 1, category: "begroeten-jezelf-voorstellen", priority: 2 },
        { id: "c-muito-prazer", type: "chunk", portuguese: "Muito prazer.", dutch: "Aangenaam.", dayIntroduced: 1, category: "begroeten-jezelf-voorstellen", priority: 2 },
      ],
    },
    {
      id: "d01-listening",
      lessonDay: 1,
      type: "listening",
      estimatedMinutes: 10,
      items: [
        { id: "c-ola-bom-dia", type: "chunk", portuguese: "Olá, bom dia.", dutch: "Hallo, goedemorgen.", dayIntroduced: 1, category: "begroeten-jezelf-voorstellen", priority: 2 },
        { id: "c-como-te-chamas", type: "chunk", portuguese: "Como te chamas?", dutch: "Hoe heet je?", dayIntroduced: 1, category: "begroeten-jezelf-voorstellen", priority: 2 },
        { id: "c-chamo-me-duran", type: "chunk", portuguese: "Chamo-me Duran.", dutch: "Ik heet Duran.", dayIntroduced: 1, category: "begroeten-jezelf-voorstellen", priority: 2 },
        { id: "c-sou-neerlandes", type: "chunk", portuguese: "Sou neerlandês.", dutch: "Ik ben Nederlands.", dayIntroduced: 1, category: "begroeten-jezelf-voorstellen", priority: 2 },
        { id: "c-sou-dos-paises-baixos", type: "chunk", portuguese: "Sou dos Países Baixos.", dutch: "Ik kom uit Nederland.", dayIntroduced: 1, category: "begroeten-jezelf-voorstellen", priority: 2 },
        { id: "c-estou-a-aprender-portugues", type: "chunk", portuguese: "Estou a aprender português.", dutch: "Ik ben Portugees aan het leren.", dayIntroduced: 1, category: "begroeten-jezelf-voorstellen", priority: 2 },
      ],
    },
    {
      id: "d01-grammar",
      lessonDay: 1,
      type: "grammar",
      estimatedMinutes: 5,
      items: [],
      notes: [
        {
          title: "Grammatica",
          body: ["ser voor identiteit."],
          points: ["eu sou","tu és"],
        },
      ],
    },
    {
      id: "d01-speaking",
      lessonDay: 1,
      type: "speaking",
      estimatedMinutes: 15,
      items: [
        { id: "c-ola-bom-dia", type: "chunk", portuguese: "Olá, bom dia.", dutch: "Hallo, goedemorgen.", dayIntroduced: 1, category: "begroeten-jezelf-voorstellen", priority: 2 },
        { id: "c-como-te-chamas", type: "chunk", portuguese: "Como te chamas?", dutch: "Hoe heet je?", dayIntroduced: 1, category: "begroeten-jezelf-voorstellen", priority: 2 },
        { id: "c-chamo-me-duran", type: "chunk", portuguese: "Chamo-me Duran.", dutch: "Ik heet Duran.", dayIntroduced: 1, category: "begroeten-jezelf-voorstellen", priority: 2 },
        { id: "c-sou-neerlandes", type: "chunk", portuguese: "Sou neerlandês.", dutch: "Ik ben Nederlands.", dayIntroduced: 1, category: "begroeten-jezelf-voorstellen", priority: 2 },
        { id: "c-sou-dos-paises-baixos", type: "chunk", portuguese: "Sou dos Países Baixos.", dutch: "Ik kom uit Nederland.", dayIntroduced: 1, category: "begroeten-jezelf-voorstellen", priority: 2 },
      ],
      tasks: [
        {
          title: "Spreekopdracht",
          kind: "speaking",
          body: ["Stel jezelf zonder script voor met minimaal vier zinnen."],
          steps: [],
        },
      ],
    },
    {
      id: "d01-test",
      lessonDay: 1,
      type: "test",
      estimatedMinutes: 5,
      items: [
        { id: "c-ola-bom-dia", type: "chunk", portuguese: "Olá, bom dia.", dutch: "Hallo, goedemorgen.", dayIntroduced: 1, category: "begroeten-jezelf-voorstellen", priority: 2 },
        { id: "c-como-te-chamas", type: "chunk", portuguese: "Como te chamas?", dutch: "Hoe heet je?", dayIntroduced: 1, category: "begroeten-jezelf-voorstellen", priority: 2 },
        { id: "c-chamo-me-duran", type: "chunk", portuguese: "Chamo-me Duran.", dutch: "Ik heet Duran.", dayIntroduced: 1, category: "begroeten-jezelf-voorstellen", priority: 2 },
        { id: "c-sou-neerlandes", type: "chunk", portuguese: "Sou neerlandês.", dutch: "Ik ben Nederlands.", dayIntroduced: 1, category: "begroeten-jezelf-voorstellen", priority: 2 },
        { id: "c-sou-dos-paises-baixos", type: "chunk", portuguese: "Sou dos Países Baixos.", dutch: "Ik kom uit Nederland.", dayIntroduced: 1, category: "begroeten-jezelf-voorstellen", priority: 2 },
        { id: "w-ola", type: "word", portuguese: "olá", dutch: "hallo", dayIntroduced: 1, category: "begroeten-jezelf-voorstellen", priority: 1 },
        { id: "w-bom-dia", type: "word", portuguese: "bom dia", dutch: "goedemorgen", dayIntroduced: 1, category: "begroeten-jezelf-voorstellen", priority: 1 },
        { id: "w-boa-tarde", type: "word", portuguese: "boa tarde", dutch: "goedemiddag", dayIntroduced: 1, category: "begroeten-jezelf-voorstellen", priority: 1 },
        { id: "w-boa-noite", type: "word", portuguese: "boa noite", dutch: "goedenavond / goedenacht", dayIntroduced: 1, category: "begroeten-jezelf-voorstellen", priority: 1 },
        { id: "w-ate-logo", type: "word", portuguese: "até logo", dutch: "tot later", dayIntroduced: 1, category: "begroeten-jezelf-voorstellen", priority: 1 },
      ],
    },
  ],
};
