// Generated by scripts/build-content.mjs — do not edit by hand.
// Source: content/lessons/*.md

import type { LessonDay } from '@/types';

export const day29: LessonDay = {
  day: 29,
  title: "Een volledige dag in Portugal",
  goal: "alle voorgaande vaardigheden combineren in één doorlopende simulatie.",
  checkpoint: false,
  modules: [
    {
      id: "d29-speaking",
      lessonDay: 29,
      type: "speaking",
      estimatedMinutes: 15,
      items: [],
      tasks: [
        {
          title: "Scenario 1 — Ochtend",
          kind: "speaking",
          body: [],
          steps: ["vraag hoe laat het ontbijt is","bestel koffie","maak smalltalk","vraag de route naar het station"],
        },
        {
          title: "Scenario 2 — Vervoer",
          kind: "speaking",
          body: [],
          steps: ["koop een kaartje","vraag het perron","controleer bestemming","reageer op vertraging"],
        },
        {
          title: "Scenario 3 — Lunch",
          kind: "speaking",
          body: [],
          steps: ["vraag een tafel","vraag een aanbeveling","bestel","geef een mening over het eten","betaal"],
        },
        {
          title: "Scenario 4 — Werk",
          kind: "speaking",
          body: [],
          steps: ["stel jezelf voor","praat over je werk","beschrijf een project","stel minimaal twee vragen"],
        },
        {
          title: "Scenario 5 — Sociaal",
          kind: "speaking",
          body: [],
          steps: ["vertel waar je vandaan komt","vergelijk Nederland en Portugal","praat over reizen","maak plannen voor de avond"],
        },
        {
          title: "Dagdoel",
          kind: "speaking",
          body: ["10–15 minuten communiceren zonder Nederlands of Engels. Fouten, zelfcorrectie en omschrijven zijn toegestaan; direct opgeven niet."],
          steps: [],
        },
      ],
    },
  ],
};
