// Generated by scripts/build-content.mjs — do not edit by hand.
// Source: content/lessons/*.md

import type { LessonDay } from '@/types';

export const day11: LessonDay = {
  day: 11,
  title: "In een restaurant",
  goal: "een restaurantbezoek grotendeels in het Portugees afhandelen.",
  checkpoint: false,
  modules: [
    {
      id: "d11-vocabulary",
      lessonDay: 11,
      type: "vocabulary",
      estimatedMinutes: 8,
      items: [
        { id: "w-restaurante", type: "word", portuguese: "restaurante", dutch: "restaurant", dayIntroduced: 11, category: "in-een-restaurant", priority: 1 },
        { id: "w-mesa", type: "word", portuguese: "mesa", dutch: "tafel", dayIntroduced: 11, category: "in-een-restaurant", priority: 1 },
        { id: "w-ementa", type: "word", portuguese: "ementa", dutch: "menukaart", dayIntroduced: 11, category: "in-een-restaurant", priority: 1 },
        { id: "w-entrada", type: "word", portuguese: "entrada", dutch: "voorgerecht", dayIntroduced: 11, category: "in-een-restaurant", priority: 1 },
        { id: "w-prato", type: "word", portuguese: "prato", dutch: "gerecht", dayIntroduced: 11, category: "in-een-restaurant", priority: 1 },
        { id: "w-sobremesa", type: "word", portuguese: "sobremesa", dutch: "dessert", dayIntroduced: 11, category: "in-een-restaurant", priority: 1 },
        { id: "w-peixe", type: "word", portuguese: "peixe", dutch: "vis", dayIntroduced: 11, category: "in-een-restaurant", priority: 1 },
        { id: "w-carne", type: "word", portuguese: "carne", dutch: "vlees", dayIntroduced: 11, category: "in-een-restaurant", priority: 1 },
        { id: "w-vegetariano", type: "word", portuguese: "vegetariano", dutch: "vegetarisch", dayIntroduced: 11, category: "in-een-restaurant", priority: 1 },
        { id: "w-conta", type: "word", portuguese: "conta", dutch: "rekening", dayIntroduced: 11, category: "in-een-restaurant", priority: 1 },
        { id: "w-pedir", type: "word", portuguese: "pedir", dutch: "bestellen / vragen", dayIntroduced: 11, category: "in-een-restaurant", priority: 1 },
        { id: "w-recomendar", type: "word", portuguese: "recomendar", dutch: "aanbevelen", dayIntroduced: 11, category: "in-een-restaurant", priority: 1 },
        { id: "w-trazer", type: "word", portuguese: "trazer", dutch: "brengen", dayIntroduced: 11, category: "in-een-restaurant", priority: 1 },
        { id: "w-sem", type: "word", portuguese: "sem", dutch: "zonder", dayIntroduced: 11, category: "in-een-restaurant", priority: 1 },
        { id: "w-com", type: "word", portuguese: "com", dutch: "met", dayIntroduced: 6, category: "familie-partner-vrienden", priority: 1 },
      ],
    },
    {
      id: "d11-chunks",
      lessonDay: 11,
      type: "chunks",
      estimatedMinutes: 7,
      items: [
        { id: "c-tem-uma-mesa-para-dois", type: "chunk", portuguese: "Tem uma mesa para dois?", dutch: "Heeft u een tafel voor twee?", dayIntroduced: 11, category: "in-een-restaurant", priority: 2 },
        { id: "c-pode-trazer-a-ementa-por-favor", type: "chunk", portuguese: "Pode trazer a ementa, por favor?", dutch: "Kunt u de kaart brengen?", dayIntroduced: 11, category: "in-een-restaurant", priority: 2 },
        { id: "c-o-que-recomenda", type: "chunk", portuguese: "O que recomenda?", dutch: "Wat raadt u aan?", dayIntroduced: 11, category: "in-een-restaurant", priority: 2 },
        { id: "c-queria-este-prato", type: "chunk", portuguese: "Queria este prato.", dutch: "Ik zou graag dit gerecht willen.", dayIntroduced: 11, category: "in-een-restaurant", priority: 2 },
        { id: "c-para-mim-o-peixe", type: "chunk", portuguese: "Para mim, o peixe.", dutch: "Voor mij de vis.", dayIntroduced: 11, category: "in-een-restaurant", priority: 2 },
        { id: "c-sem-cebola-por-favor", type: "chunk", portuguese: "Sem cebola, por favor.", dutch: "Zonder ui, alstublieft.", dayIntroduced: 11, category: "in-een-restaurant", priority: 2 },
        { id: "c-a-conta-por-favor", type: "chunk", portuguese: "A conta, por favor.", dutch: "De rekening, alstublieft.", dayIntroduced: 11, category: "in-een-restaurant", priority: 2 },
        { id: "c-estava-muito-bom", type: "chunk", portuguese: "Estava muito bom.", dutch: "Het was erg lekker.", dayIntroduced: 11, category: "in-een-restaurant", priority: 2 },
      ],
    },
    {
      id: "d11-listening",
      lessonDay: 11,
      type: "listening",
      estimatedMinutes: 10,
      items: [
        { id: "c-tem-uma-mesa-para-dois", type: "chunk", portuguese: "Tem uma mesa para dois?", dutch: "Heeft u een tafel voor twee?", dayIntroduced: 11, category: "in-een-restaurant", priority: 2 },
        { id: "c-pode-trazer-a-ementa-por-favor", type: "chunk", portuguese: "Pode trazer a ementa, por favor?", dutch: "Kunt u de kaart brengen?", dayIntroduced: 11, category: "in-een-restaurant", priority: 2 },
        { id: "c-o-que-recomenda", type: "chunk", portuguese: "O que recomenda?", dutch: "Wat raadt u aan?", dayIntroduced: 11, category: "in-een-restaurant", priority: 2 },
        { id: "c-queria-este-prato", type: "chunk", portuguese: "Queria este prato.", dutch: "Ik zou graag dit gerecht willen.", dayIntroduced: 11, category: "in-een-restaurant", priority: 2 },
        { id: "c-para-mim-o-peixe", type: "chunk", portuguese: "Para mim, o peixe.", dutch: "Voor mij de vis.", dayIntroduced: 11, category: "in-een-restaurant", priority: 2 },
        { id: "c-sem-cebola-por-favor", type: "chunk", portuguese: "Sem cebola, por favor.", dutch: "Zonder ui, alstublieft.", dayIntroduced: 11, category: "in-een-restaurant", priority: 2 },
      ],
    },
    {
      id: "d11-grammar",
      lessonDay: 11,
      type: "grammar",
      estimatedMinutes: 5,
      items: [],
      notes: [
        {
          title: "Grammatica",
          body: ["poder + infinitief voor beleefde verzoeken."],
          points: [],
        },
      ],
    },
    {
      id: "d11-speaking",
      lessonDay: 11,
      type: "speaking",
      estimatedMinutes: 15,
      items: [
        { id: "c-tem-uma-mesa-para-dois", type: "chunk", portuguese: "Tem uma mesa para dois?", dutch: "Heeft u een tafel voor twee?", dayIntroduced: 11, category: "in-een-restaurant", priority: 2 },
        { id: "c-pode-trazer-a-ementa-por-favor", type: "chunk", portuguese: "Pode trazer a ementa, por favor?", dutch: "Kunt u de kaart brengen?", dayIntroduced: 11, category: "in-een-restaurant", priority: 2 },
        { id: "c-o-que-recomenda", type: "chunk", portuguese: "O que recomenda?", dutch: "Wat raadt u aan?", dayIntroduced: 11, category: "in-een-restaurant", priority: 2 },
        { id: "c-queria-este-prato", type: "chunk", portuguese: "Queria este prato.", dutch: "Ik zou graag dit gerecht willen.", dayIntroduced: 11, category: "in-een-restaurant", priority: 2 },
        { id: "c-para-mim-o-peixe", type: "chunk", portuguese: "Para mim, o peixe.", dutch: "Voor mij de vis.", dayIntroduced: 11, category: "in-een-restaurant", priority: 2 },
      ],
      tasks: [
        {
          title: "Spreekopdracht",
          kind: "speaking",
          body: ["Voer een restaurantbezoek uit van tafel vragen tot betalen."],
          steps: [],
        },
      ],
    },
  ],
};
