// Generated by scripts/build-content.mjs — do not edit by hand.
// Source: content/lessons/*.md

import type { LessonDay } from '@/types';

export const day26: LessonDay = {
  day: 26,
  title: "Zakelijk kennismaken",
  goal: "jezelf professioneel introduceren zonder direct naar Engels over te schakelen.",
  checkpoint: false,
  modules: [
    {
      id: "d26-vocabulary",
      lessonDay: 26,
      type: "vocabulary",
      estimatedMinutes: 8,
      items: [
        { id: "w-profissao", type: "word", portuguese: "profissão", dutch: "beroep", dayIntroduced: 26, category: "zakelijk-kennismaken", priority: 1 },
        { id: "w-empresa", type: "word", portuguese: "empresa", dutch: "bedrijf", dayIntroduced: 7, category: "werk-beroep", priority: 1 },
        { id: "w-equipa", type: "word", portuguese: "equipa", dutch: "team", dayIntroduced: 26, category: "zakelijk-kennismaken", priority: 1 },
        { id: "w-cliente", type: "word", portuguese: "cliente", dutch: "klant", dayIntroduced: 7, category: "werk-beroep", priority: 1 },
        { id: "w-reuniao", type: "word", portuguese: "reunião", dutch: "vergadering", dayIntroduced: 7, category: "werk-beroep", priority: 1 },
        { id: "w-projeto", type: "word", portuguese: "projeto", dutch: "project", dayIntroduced: 7, category: "werk-beroep", priority: 1 },
        { id: "w-mercado", type: "word", portuguese: "mercado", dutch: "markt", dayIntroduced: 26, category: "zakelijk-kennismaken", priority: 1 },
        { id: "w-objetivo", type: "word", portuguese: "objetivo", dutch: "doel", dayIntroduced: 26, category: "zakelijk-kennismaken", priority: 1 },
        { id: "w-estrategia", type: "word", portuguese: "estratégia", dutch: "strategie", dayIntroduced: 26, category: "zakelijk-kennismaken", priority: 1 },
        { id: "w-resultado", type: "word", portuguese: "resultado", dutch: "resultaat", dayIntroduced: 26, category: "zakelijk-kennismaken", priority: 1 },
        { id: "w-marketing", type: "word", portuguese: "marketing", dutch: "marketing", dayIntroduced: 7, category: "werk-beroep", priority: 1 },
        { id: "w-publicidade", type: "word", portuguese: "publicidade", dutch: "advertising / reclame", dayIntroduced: 7, category: "werk-beroep", priority: 1 },
        { id: "w-digital", type: "word", portuguese: "digital", dutch: "digitaal", dayIntroduced: 26, category: "zakelijk-kennismaken", priority: 1 },
        { id: "w-trabalhar", type: "word", portuguese: "trabalhar", dutch: "werken", dayIntroduced: 7, category: "werk-beroep", priority: 1 },
        { id: "w-gerir", type: "word", portuguese: "gerir", dutch: "beheren", dayIntroduced: 26, category: "zakelijk-kennismaken", priority: 1 },
      ],
    },
    {
      id: "d26-chunks",
      lessonDay: 26,
      type: "chunks",
      estimatedMinutes: 7,
      items: [
        { id: "c-trabalho-em-marketing-digital", type: "chunk", portuguese: "Trabalho em marketing digital.", dutch: "Ik werk in digitale marketing.", dayIntroduced: 26, category: "zakelijk-kennismaken", priority: 2 },
        { id: "c-trabalho-sobretudo-com-publicidade-online", type: "chunk", portuguese: "Trabalho sobretudo com publicidade online.", dutch: "Ik werk vooral met online advertising.", dayIntroduced: 26, category: "zakelijk-kennismaken", priority: 2 },
        { id: "c-trabalho-com-varios-clientes", type: "chunk", portuguese: "Trabalho com vários clientes.", dutch: "Ik werk met verschillende klanten.", dayIntroduced: 26, category: "zakelijk-kennismaken", priority: 2 },
        { id: "c-faco-parte-de-uma-equipa", type: "chunk", portuguese: "Faço parte de uma equipa.", dutch: "Ik maak deel uit van een team.", dayIntroduced: 26, category: "zakelijk-kennismaken", priority: 2 },
        { id: "c-estou-aqui-por-causa-de-uma-reuniao", type: "chunk", portuguese: "Estou aqui por causa de uma reunião.", dutch: "Ik ben hier voor een vergadering.", dayIntroduced: 26, category: "zakelijk-kennismaken", priority: 2 },
        { id: "c-estamos-a-trabalhar-num-projeto", type: "chunk", portuguese: "Estamos a trabalhar num projeto.", dutch: "We werken aan een project.", dayIntroduced: 26, category: "zakelijk-kennismaken", priority: 2 },
        { id: "c-qual-e-a-sua-funcao", type: "chunk", portuguese: "Qual é a sua função?", dutch: "Wat is uw functie?", dayIntroduced: 26, category: "zakelijk-kennismaken", priority: 2 },
        { id: "c-muito-prazer", type: "chunk", portuguese: "Muito prazer.", dutch: "Aangenaam.", dayIntroduced: 1, category: "begroeten-jezelf-voorstellen", priority: 2 },
      ],
    },
    {
      id: "d26-listening",
      lessonDay: 26,
      type: "listening",
      estimatedMinutes: 10,
      items: [
        { id: "c-trabalho-em-marketing-digital", type: "chunk", portuguese: "Trabalho em marketing digital.", dutch: "Ik werk in digitale marketing.", dayIntroduced: 26, category: "zakelijk-kennismaken", priority: 2 },
        { id: "c-trabalho-sobretudo-com-publicidade-online", type: "chunk", portuguese: "Trabalho sobretudo com publicidade online.", dutch: "Ik werk vooral met online advertising.", dayIntroduced: 26, category: "zakelijk-kennismaken", priority: 2 },
        { id: "c-trabalho-com-varios-clientes", type: "chunk", portuguese: "Trabalho com vários clientes.", dutch: "Ik werk met verschillende klanten.", dayIntroduced: 26, category: "zakelijk-kennismaken", priority: 2 },
        { id: "c-faco-parte-de-uma-equipa", type: "chunk", portuguese: "Faço parte de uma equipa.", dutch: "Ik maak deel uit van een team.", dayIntroduced: 26, category: "zakelijk-kennismaken", priority: 2 },
        { id: "c-estou-aqui-por-causa-de-uma-reuniao", type: "chunk", portuguese: "Estou aqui por causa de uma reunião.", dutch: "Ik ben hier voor een vergadering.", dayIntroduced: 26, category: "zakelijk-kennismaken", priority: 2 },
        { id: "c-estamos-a-trabalhar-num-projeto", type: "chunk", portuguese: "Estamos a trabalhar num projeto.", dutch: "We werken aan een project.", dayIntroduced: 26, category: "zakelijk-kennismaken", priority: 2 },
      ],
    },
    {
      id: "d26-grammar",
      lessonDay: 26,
      type: "grammar",
      estimatedMinutes: 5,
      items: [],
      notes: [
        {
          title: "Taalgebruik",
          body: ["Gebruik in zakelijke context beleefde vormen zoals Pode…? en Qual é a sua…?, zonder voortdurend expliciet você te gebruiken."],
          points: [],
        },
      ],
    },
    {
      id: "d26-speaking",
      lessonDay: 26,
      type: "speaking",
      estimatedMinutes: 15,
      items: [
        { id: "c-trabalho-em-marketing-digital", type: "chunk", portuguese: "Trabalho em marketing digital.", dutch: "Ik werk in digitale marketing.", dayIntroduced: 26, category: "zakelijk-kennismaken", priority: 2 },
        { id: "c-trabalho-sobretudo-com-publicidade-online", type: "chunk", portuguese: "Trabalho sobretudo com publicidade online.", dutch: "Ik werk vooral met online advertising.", dayIntroduced: 26, category: "zakelijk-kennismaken", priority: 2 },
        { id: "c-trabalho-com-varios-clientes", type: "chunk", portuguese: "Trabalho com vários clientes.", dutch: "Ik werk met verschillende klanten.", dayIntroduced: 26, category: "zakelijk-kennismaken", priority: 2 },
        { id: "c-faco-parte-de-uma-equipa", type: "chunk", portuguese: "Faço parte de uma equipa.", dutch: "Ik maak deel uit van een team.", dayIntroduced: 26, category: "zakelijk-kennismaken", priority: 2 },
        { id: "c-estou-aqui-por-causa-de-uma-reuniao", type: "chunk", portuguese: "Estou aqui por causa de uma reunião.", dutch: "Ik ben hier voor een vergadering.", dayIntroduced: 26, category: "zakelijk-kennismaken", priority: 2 },
      ],
      tasks: [
        {
          title: "Spreekopdracht",
          kind: "speaking",
          body: ["Stel jezelf zakelijk voor en stel drie eenvoudige professionele vragen."],
          steps: [],
        },
      ],
    },
    {
      id: "d26-test",
      lessonDay: 26,
      type: "test",
      estimatedMinutes: 5,
      items: [
        { id: "c-trabalho-em-marketing-digital", type: "chunk", portuguese: "Trabalho em marketing digital.", dutch: "Ik werk in digitale marketing.", dayIntroduced: 26, category: "zakelijk-kennismaken", priority: 2 },
        { id: "c-trabalho-sobretudo-com-publicidade-online", type: "chunk", portuguese: "Trabalho sobretudo com publicidade online.", dutch: "Ik werk vooral met online advertising.", dayIntroduced: 26, category: "zakelijk-kennismaken", priority: 2 },
        { id: "c-trabalho-com-varios-clientes", type: "chunk", portuguese: "Trabalho com vários clientes.", dutch: "Ik werk met verschillende klanten.", dayIntroduced: 26, category: "zakelijk-kennismaken", priority: 2 },
        { id: "c-faco-parte-de-uma-equipa", type: "chunk", portuguese: "Faço parte de uma equipa.", dutch: "Ik maak deel uit van een team.", dayIntroduced: 26, category: "zakelijk-kennismaken", priority: 2 },
        { id: "c-estou-aqui-por-causa-de-uma-reuniao", type: "chunk", portuguese: "Estou aqui por causa de uma reunião.", dutch: "Ik ben hier voor een vergadering.", dayIntroduced: 26, category: "zakelijk-kennismaken", priority: 2 },
        { id: "w-profissao", type: "word", portuguese: "profissão", dutch: "beroep", dayIntroduced: 26, category: "zakelijk-kennismaken", priority: 1 },
        { id: "w-empresa", type: "word", portuguese: "empresa", dutch: "bedrijf", dayIntroduced: 7, category: "werk-beroep", priority: 1 },
        { id: "w-equipa", type: "word", portuguese: "equipa", dutch: "team", dayIntroduced: 26, category: "zakelijk-kennismaken", priority: 1 },
        { id: "w-cliente", type: "word", portuguese: "cliente", dutch: "klant", dayIntroduced: 7, category: "werk-beroep", priority: 1 },
        { id: "w-reuniao", type: "word", portuguese: "reunião", dutch: "vergadering", dayIntroduced: 7, category: "werk-beroep", priority: 1 },
      ],
    },
  ],
};
