// Generated by scripts/build-content.mjs — do not edit by hand.
// Source: content/lessons/*.md

import type { LessonDay } from '@/types';

export const day14: LessonDay = {
  day: 14,
  title: "Trein, metro & openbaar vervoer",
  goal: "zelfstandig een eenvoudige OV-reis regelen.",
  checkpoint: false,
  modules: [
    {
      id: "d14-vocabulary",
      lessonDay: 14,
      type: "vocabulary",
      estimatedMinutes: 8,
      items: [
        { id: "w-comboio", type: "word", portuguese: "comboio", dutch: "trein", dayIntroduced: 14, category: "trein-metro-openbaar-vervoer", priority: 1 },
        { id: "w-autocarro", type: "word", portuguese: "autocarro", dutch: "bus", dayIntroduced: 14, category: "trein-metro-openbaar-vervoer", priority: 1 },
        { id: "w-metro", type: "word", portuguese: "metro", dutch: "metro", dayIntroduced: 14, category: "trein-metro-openbaar-vervoer", priority: 1 },
        { id: "w-bilhete", type: "word", portuguese: "bilhete", dutch: "kaartje", dayIntroduced: 14, category: "trein-metro-openbaar-vervoer", priority: 1 },
        { id: "w-estacao", type: "word", portuguese: "estação", dutch: "station", dayIntroduced: 14, category: "trein-metro-openbaar-vervoer", priority: 1 },
        { id: "w-paragem", type: "word", portuguese: "paragem", dutch: "halte", dayIntroduced: 14, category: "trein-metro-openbaar-vervoer", priority: 1 },
        { id: "w-plataforma", type: "word", portuguese: "plataforma", dutch: "perron", dayIntroduced: 14, category: "trein-metro-openbaar-vervoer", priority: 1 },
        { id: "w-horario", type: "word", portuguese: "horário", dutch: "dienstregeling", dayIntroduced: 14, category: "trein-metro-openbaar-vervoer", priority: 1 },
        { id: "w-destino", type: "word", portuguese: "destino", dutch: "bestemming", dayIntroduced: 14, category: "trein-metro-openbaar-vervoer", priority: 1 },
        { id: "w-ida", type: "word", portuguese: "ida", dutch: "heenreis", dayIntroduced: 14, category: "trein-metro-openbaar-vervoer", priority: 1 },
        { id: "w-volta", type: "word", portuguese: "volta", dutch: "terugreis", dayIntroduced: 14, category: "trein-metro-openbaar-vervoer", priority: 1 },
        { id: "w-partir", type: "word", portuguese: "partir", dutch: "vertrekken", dayIntroduced: 14, category: "trein-metro-openbaar-vervoer", priority: 1 },
        { id: "w-chegar", type: "word", portuguese: "chegar", dutch: "aankomen", dayIntroduced: 14, category: "trein-metro-openbaar-vervoer", priority: 1 },
        { id: "w-atraso", type: "word", portuguese: "atraso", dutch: "vertraging", dayIntroduced: 14, category: "trein-metro-openbaar-vervoer", priority: 1 },
        { id: "w-mudar", type: "word", portuguese: "mudar", dutch: "overstappen / veranderen", dayIntroduced: 14, category: "trein-metro-openbaar-vervoer", priority: 1 },
      ],
    },
    {
      id: "d14-chunks",
      lessonDay: 14,
      type: "chunks",
      estimatedMinutes: 7,
      items: [
        { id: "c-queria-um-bilhete-para-lisboa", type: "chunk", portuguese: "Queria um bilhete para Lisboa.", dutch: "Ik zou graag een kaartje naar Lissabon willen.", dayIntroduced: 14, category: "trein-metro-openbaar-vervoer", priority: 2 },
        { id: "c-so-ida", type: "chunk", portuguese: "Só ida.", dutch: "Alleen heen.", dayIntroduced: 14, category: "trein-metro-openbaar-vervoer", priority: 2 },
        { id: "c-ida-e-volta", type: "chunk", portuguese: "Ida e volta.", dutch: "Retour.", dayIntroduced: 14, category: "trein-metro-openbaar-vervoer", priority: 2 },
        { id: "c-a-que-horas-parte-o-comboio", type: "chunk", portuguese: "A que horas parte o comboio?", dutch: "Hoe laat vertrekt de trein?", dayIntroduced: 14, category: "trein-metro-openbaar-vervoer", priority: 2 },
        { id: "c-a-que-horas-chega", type: "chunk", portuguese: "A que horas chega?", dutch: "Hoe laat komt hij aan?", dayIntroduced: 14, category: "trein-metro-openbaar-vervoer", priority: 2 },
        { id: "c-qual-e-a-plataforma", type: "chunk", portuguese: "Qual é a plataforma?", dutch: "Welk perron is het?", dayIntroduced: 14, category: "trein-metro-openbaar-vervoer", priority: 2 },
        { id: "c-este-comboio-vai-para-porto", type: "chunk", portuguese: "Este comboio vai para Porto?", dutch: "Gaat deze trein naar Porto?", dayIntroduced: 14, category: "trein-metro-openbaar-vervoer", priority: 2 },
        { id: "c-tenho-de-mudar-de-comboio", type: "chunk", portuguese: "Tenho de mudar de comboio?", dutch: "Moet ik overstappen?", dayIntroduced: 14, category: "trein-metro-openbaar-vervoer", priority: 2 },
      ],
    },
    {
      id: "d14-listening",
      lessonDay: 14,
      type: "listening",
      estimatedMinutes: 10,
      items: [
        { id: "c-queria-um-bilhete-para-lisboa", type: "chunk", portuguese: "Queria um bilhete para Lisboa.", dutch: "Ik zou graag een kaartje naar Lissabon willen.", dayIntroduced: 14, category: "trein-metro-openbaar-vervoer", priority: 2 },
        { id: "c-so-ida", type: "chunk", portuguese: "Só ida.", dutch: "Alleen heen.", dayIntroduced: 14, category: "trein-metro-openbaar-vervoer", priority: 2 },
        { id: "c-ida-e-volta", type: "chunk", portuguese: "Ida e volta.", dutch: "Retour.", dayIntroduced: 14, category: "trein-metro-openbaar-vervoer", priority: 2 },
        { id: "c-a-que-horas-parte-o-comboio", type: "chunk", portuguese: "A que horas parte o comboio?", dutch: "Hoe laat vertrekt de trein?", dayIntroduced: 14, category: "trein-metro-openbaar-vervoer", priority: 2 },
        { id: "c-a-que-horas-chega", type: "chunk", portuguese: "A que horas chega?", dutch: "Hoe laat komt hij aan?", dayIntroduced: 14, category: "trein-metro-openbaar-vervoer", priority: 2 },
        { id: "c-qual-e-a-plataforma", type: "chunk", portuguese: "Qual é a plataforma?", dutch: "Welk perron is het?", dayIntroduced: 14, category: "trein-metro-openbaar-vervoer", priority: 2 },
      ],
    },
    {
      id: "d14-grammar",
      lessonDay: 14,
      type: "grammar",
      estimatedMinutes: 5,
      items: [],
      notes: [
        {
          title: "pt-PT focus",
          body: ["Gebruik in Portugal comboio en autocarro."],
          points: [],
        },
      ],
    },
    {
      id: "d14-speaking",
      lessonDay: 14,
      type: "speaking",
      estimatedMinutes: 15,
      items: [
        { id: "c-queria-um-bilhete-para-lisboa", type: "chunk", portuguese: "Queria um bilhete para Lisboa.", dutch: "Ik zou graag een kaartje naar Lissabon willen.", dayIntroduced: 14, category: "trein-metro-openbaar-vervoer", priority: 2 },
        { id: "c-so-ida", type: "chunk", portuguese: "Só ida.", dutch: "Alleen heen.", dayIntroduced: 14, category: "trein-metro-openbaar-vervoer", priority: 2 },
        { id: "c-ida-e-volta", type: "chunk", portuguese: "Ida e volta.", dutch: "Retour.", dayIntroduced: 14, category: "trein-metro-openbaar-vervoer", priority: 2 },
        { id: "c-a-que-horas-parte-o-comboio", type: "chunk", portuguese: "A que horas parte o comboio?", dutch: "Hoe laat vertrekt de trein?", dayIntroduced: 14, category: "trein-metro-openbaar-vervoer", priority: 2 },
        { id: "c-a-que-horas-chega", type: "chunk", portuguese: "A que horas chega?", dutch: "Hoe laat komt hij aan?", dayIntroduced: 14, category: "trein-metro-openbaar-vervoer", priority: 2 },
      ],
      tasks: [
        {
          title: "Spreekopdracht",
          kind: "speaking",
          body: ["Koop een retourticket, controleer tijd, bestemming en perron."],
          steps: [],
        },
      ],
    },
    {
      id: "d14-test",
      lessonDay: 14,
      type: "test",
      estimatedMinutes: 5,
      items: [
        { id: "c-queria-um-bilhete-para-lisboa", type: "chunk", portuguese: "Queria um bilhete para Lisboa.", dutch: "Ik zou graag een kaartje naar Lissabon willen.", dayIntroduced: 14, category: "trein-metro-openbaar-vervoer", priority: 2 },
        { id: "c-so-ida", type: "chunk", portuguese: "Só ida.", dutch: "Alleen heen.", dayIntroduced: 14, category: "trein-metro-openbaar-vervoer", priority: 2 },
        { id: "c-ida-e-volta", type: "chunk", portuguese: "Ida e volta.", dutch: "Retour.", dayIntroduced: 14, category: "trein-metro-openbaar-vervoer", priority: 2 },
        { id: "c-a-que-horas-parte-o-comboio", type: "chunk", portuguese: "A que horas parte o comboio?", dutch: "Hoe laat vertrekt de trein?", dayIntroduced: 14, category: "trein-metro-openbaar-vervoer", priority: 2 },
        { id: "c-a-que-horas-chega", type: "chunk", portuguese: "A que horas chega?", dutch: "Hoe laat komt hij aan?", dayIntroduced: 14, category: "trein-metro-openbaar-vervoer", priority: 2 },
        { id: "w-comboio", type: "word", portuguese: "comboio", dutch: "trein", dayIntroduced: 14, category: "trein-metro-openbaar-vervoer", priority: 1 },
        { id: "w-autocarro", type: "word", portuguese: "autocarro", dutch: "bus", dayIntroduced: 14, category: "trein-metro-openbaar-vervoer", priority: 1 },
        { id: "w-metro", type: "word", portuguese: "metro", dutch: "metro", dayIntroduced: 14, category: "trein-metro-openbaar-vervoer", priority: 1 },
        { id: "w-bilhete", type: "word", portuguese: "bilhete", dutch: "kaartje", dayIntroduced: 14, category: "trein-metro-openbaar-vervoer", priority: 1 },
        { id: "w-estacao", type: "word", portuguese: "estação", dutch: "station", dayIntroduced: 14, category: "trein-metro-openbaar-vervoer", priority: 1 },
      ],
    },
  ],
};
