// Generated by scripts/build-content.mjs — do not edit by hand.
// Source: content/lessons/*.md

import type { LessonDay } from '@/types';

export const day18: LessonDay = {
  day: 18,
  title: "Morgen en de toekomst",
  goal: "plannen beschrijven zonder ingewikkelde toekomstige werkwoordsvormen.",
  checkpoint: false,
  modules: [
    {
      id: "d18-vocabulary",
      lessonDay: 18,
      type: "vocabulary",
      estimatedMinutes: 8,
      items: [
        { id: "w-amanha", type: "word", portuguese: "amanhã", dutch: "morgen", dayIntroduced: 18, category: "morgen-en-de-toekomst", priority: 1 },
        { id: "w-proximo", type: "word", portuguese: "próximo", dutch: "volgende", dayIntroduced: 18, category: "morgen-en-de-toekomst", priority: 1 },
        { id: "w-plano", type: "word", portuguese: "plano", dutch: "plan", dayIntroduced: 18, category: "morgen-en-de-toekomst", priority: 1 },
        { id: "w-fim-de-semana", type: "word", portuguese: "fim de semana", dutch: "weekend", dayIntroduced: 18, category: "morgen-en-de-toekomst", priority: 1 },
        { id: "w-descansar", type: "word", portuguese: "descansar", dutch: "uitrusten", dayIntroduced: 18, category: "morgen-en-de-toekomst", priority: 1 },
        { id: "w-jantar", type: "word", portuguese: "jantar", dutch: "avondeten", dayIntroduced: 18, category: "morgen-en-de-toekomst", priority: 1 },
        { id: "w-encontrar", type: "word", portuguese: "encontrar", dutch: "ontmoeten", dayIntroduced: 18, category: "morgen-en-de-toekomst", priority: 1 },
        { id: "w-viajar", type: "word", portuguese: "viajar", dutch: "reizen", dayIntroduced: 8, category: "hobby-s-vrije-tijd", priority: 1 },
        { id: "w-trabalhar", type: "word", portuguese: "trabalhar", dutch: "werken", dayIntroduced: 7, category: "werk-beroep", priority: 1 },
        { id: "w-visitar", type: "word", portuguese: "visitar", dutch: "bezoeken", dayIntroduced: 16, category: "wat-deed-je-gisteren", priority: 1 },
        { id: "w-sair", type: "word", portuguese: "sair", dutch: "uitgaan", dayIntroduced: 16, category: "wat-deed-je-gisteren", priority: 1 },
        { id: "w-ficar", type: "word", portuguese: "ficar", dutch: "blijven", dayIntroduced: 16, category: "wat-deed-je-gisteren", priority: 1 },
        { id: "w-comprar", type: "word", portuguese: "comprar", dutch: "kopen", dayIntroduced: 12, category: "winkelen", priority: 1 },
        { id: "w-fazer", type: "word", portuguese: "fazer", dutch: "doen", dayIntroduced: 7, category: "werk-beroep", priority: 1 },
        { id: "w-ir", type: "word", portuguese: "ir", dutch: "gaan", dayIntroduced: 9, category: "dagelijkse-routine", priority: 1 },
      ],
    },
    {
      id: "d18-chunks",
      lessonDay: 18,
      type: "chunks",
      estimatedMinutes: 7,
      items: [
        { id: "c-amanha-vou-trabalhar", type: "chunk", portuguese: "Amanhã vou trabalhar.", dutch: "Morgen ga ik werken.", dayIntroduced: 18, category: "morgen-en-de-toekomst", priority: 2 },
        { id: "c-depois-vou-jantar", type: "chunk", portuguese: "Depois vou jantar.", dutch: "Daarna ga ik avondeten.", dayIntroduced: 18, category: "morgen-en-de-toekomst", priority: 2 },
        { id: "c-vou-visitar-lisboa", type: "chunk", portuguese: "Vou visitar Lisboa.", dutch: "Ik ga Lissabon bezoeken.", dayIntroduced: 18, category: "morgen-en-de-toekomst", priority: 2 },
        { id: "c-este-fim-de-semana-vou-descansar", type: "chunk", portuguese: "Este fim de semana vou descansar.", dutch: "Dit weekend ga ik uitrusten.", dayIntroduced: 18, category: "morgen-en-de-toekomst", priority: 2 },
        { id: "c-o-que-vais-fazer-amanha", type: "chunk", portuguese: "O que vais fazer amanhã?", dutch: "Wat ga je morgen doen?", dayIntroduced: 18, category: "morgen-en-de-toekomst", priority: 2 },
        { id: "c-vais-sair-esta-noite", type: "chunk", portuguese: "Vais sair esta noite?", dutch: "Ga je vanavond uit?", dayIntroduced: 18, category: "morgen-en-de-toekomst", priority: 2 },
        { id: "c-vou-ficar-em-casa", type: "chunk", portuguese: "Vou ficar em casa.", dutch: "Ik blijf thuis.", dayIntroduced: 18, category: "morgen-en-de-toekomst", priority: 2 },
        { id: "c-ainda-nao-sei", type: "chunk", portuguese: "Ainda não sei.", dutch: "Ik weet het nog niet.", dayIntroduced: 18, category: "morgen-en-de-toekomst", priority: 2 },
      ],
    },
    {
      id: "d18-grammar",
      lessonDay: 18,
      type: "grammar",
      estimatedMinutes: 5,
      items: [],
      notes: [
        {
          title: "Grammatica",
          body: ["Gebruik ir + infinitief als standaardconstructie voor de nabije toekomst."],
          points: [],
        },
      ],
    },
    {
      id: "d18-speaking",
      lessonDay: 18,
      type: "speaking",
      estimatedMinutes: 15,
      items: [],
      tasks: [
        {
          title: "Spreekopdracht",
          kind: "speaking",
          body: ["Vertel wat je morgen en komend weekend gaat doen."],
          steps: [],
        },
      ],
    },
  ],
};
