// Generated by scripts/build-content.mjs — do not edit by hand.
// Source: content/lessons/*.md

import type { LessonDay } from '@/types';

export const day16: LessonDay = {
  day: 16,
  title: "Wat deed je gisteren?",
  goal: "voor het eerst over gebeurtenissen in het verleden praten.",
  checkpoint: false,
  modules: [
    {
      id: "d16-vocabulary",
      lessonDay: 16,
      type: "vocabulary",
      estimatedMinutes: 8,
      items: [
        { id: "w-ontem", type: "word", portuguese: "ontem", dutch: "gisteren", dayIntroduced: 16, category: "wat-deed-je-gisteren", priority: 1 },
        { id: "w-depois", type: "word", portuguese: "depois", dutch: "daarna", dayIntroduced: 16, category: "wat-deed-je-gisteren", priority: 1 },
        { id: "w-primeiro", type: "word", portuguese: "primeiro", dutch: "eerst", dayIntroduced: 16, category: "wat-deed-je-gisteren", priority: 1 },
        { id: "w-voltar", type: "word", portuguese: "voltar", dutch: "teruggaan", dayIntroduced: 16, category: "wat-deed-je-gisteren", priority: 1 },
        { id: "w-chegar", type: "word", portuguese: "chegar", dutch: "aankomen", dayIntroduced: 14, category: "trein-metro-openbaar-vervoer", priority: 1 },
        { id: "w-ficar", type: "word", portuguese: "ficar", dutch: "blijven / verblijven", dayIntroduced: 16, category: "wat-deed-je-gisteren", priority: 1 },
        { id: "w-visitar", type: "word", portuguese: "visitar", dutch: "bezoeken", dayIntroduced: 16, category: "wat-deed-je-gisteren", priority: 1 },
        { id: "w-trabalhar", type: "word", portuguese: "trabalhar", dutch: "werken", dayIntroduced: 7, category: "werk-beroep", priority: 1 },
        { id: "w-comer", type: "word", portuguese: "comer", dutch: "eten", dayIntroduced: 4, category: "in-een-cafe-bestellen", priority: 1 },
        { id: "w-beber", type: "word", portuguese: "beber", dutch: "drinken", dayIntroduced: 4, category: "in-een-cafe-bestellen", priority: 1 },
        { id: "w-fazer", type: "word", portuguese: "fazer", dutch: "doen", dayIntroduced: 7, category: "werk-beroep", priority: 1 },
        { id: "w-ir", type: "word", portuguese: "ir", dutch: "gaan", dayIntroduced: 9, category: "dagelijkse-routine", priority: 1 },
        { id: "w-ver", type: "word", portuguese: "ver", dutch: "zien", dayIntroduced: 16, category: "wat-deed-je-gisteren", priority: 1 },
        { id: "w-comprar", type: "word", portuguese: "comprar", dutch: "kopen", dayIntroduced: 12, category: "winkelen", priority: 1 },
        { id: "w-sair", type: "word", portuguese: "sair", dutch: "uitgaan / vertrekken", dayIntroduced: 16, category: "wat-deed-je-gisteren", priority: 1 },
      ],
    },
    {
      id: "d16-chunks",
      lessonDay: 16,
      type: "chunks",
      estimatedMinutes: 7,
      items: [
        { id: "c-ontem-trabalhei", type: "chunk", portuguese: "Ontem trabalhei.", dutch: "Gisteren heb ik gewerkt.", dayIntroduced: 16, category: "wat-deed-je-gisteren", priority: 2 },
        { id: "c-ontem-fui-ao-centro", type: "chunk", portuguese: "Ontem fui ao centro.", dutch: "Gisteren ging ik naar het centrum.", dayIntroduced: 16, category: "wat-deed-je-gisteren", priority: 2 },
        { id: "c-depois-fui-a-um-restaurante", type: "chunk", portuguese: "Depois fui a um restaurante.", dutch: "Daarna ging ik naar een restaurant.", dayIntroduced: 16, category: "wat-deed-je-gisteren", priority: 2 },
        { id: "c-comi-peixe", type: "chunk", portuguese: "Comi peixe.", dutch: "Ik at vis.", dayIntroduced: 16, category: "wat-deed-je-gisteren", priority: 2 },
        { id: "c-bebi-vinho", type: "chunk", portuguese: "Bebi vinho.", dutch: "Ik dronk wijn.", dayIntroduced: 16, category: "wat-deed-je-gisteren", priority: 2 },
        { id: "c-vi-um-filme", type: "chunk", portuguese: "Vi um filme.", dutch: "Ik zag een film.", dayIntroduced: 16, category: "wat-deed-je-gisteren", priority: 2 },
        { id: "c-fiquei-em-casa", type: "chunk", portuguese: "Fiquei em casa.", dutch: "Ik bleef thuis.", dayIntroduced: 16, category: "wat-deed-je-gisteren", priority: 2 },
        { id: "c-depois-voltei-para-casa", type: "chunk", portuguese: "Depois voltei para casa.", dutch: "Daarna ging ik terug naar huis.", dayIntroduced: 16, category: "wat-deed-je-gisteren", priority: 2 },
      ],
    },
    {
      id: "d16-listening",
      lessonDay: 16,
      type: "listening",
      estimatedMinutes: 10,
      items: [
        { id: "c-ontem-trabalhei", type: "chunk", portuguese: "Ontem trabalhei.", dutch: "Gisteren heb ik gewerkt.", dayIntroduced: 16, category: "wat-deed-je-gisteren", priority: 2 },
        { id: "c-ontem-fui-ao-centro", type: "chunk", portuguese: "Ontem fui ao centro.", dutch: "Gisteren ging ik naar het centrum.", dayIntroduced: 16, category: "wat-deed-je-gisteren", priority: 2 },
        { id: "c-depois-fui-a-um-restaurante", type: "chunk", portuguese: "Depois fui a um restaurante.", dutch: "Daarna ging ik naar een restaurant.", dayIntroduced: 16, category: "wat-deed-je-gisteren", priority: 2 },
        { id: "c-comi-peixe", type: "chunk", portuguese: "Comi peixe.", dutch: "Ik at vis.", dayIntroduced: 16, category: "wat-deed-je-gisteren", priority: 2 },
        { id: "c-bebi-vinho", type: "chunk", portuguese: "Bebi vinho.", dutch: "Ik dronk wijn.", dayIntroduced: 16, category: "wat-deed-je-gisteren", priority: 2 },
        { id: "c-vi-um-filme", type: "chunk", portuguese: "Vi um filme.", dutch: "Ik zag een film.", dayIntroduced: 16, category: "wat-deed-je-gisteren", priority: 2 },
      ],
    },
    {
      id: "d16-grammar",
      lessonDay: 16,
      type: "grammar",
      estimatedMinutes: 5,
      items: [],
      notes: [
        {
          title: "Belangrijke verleden vormen",
          body: [],
          points: ["ir → fui","fazer → fiz","ver → vi","comer → comi","beber → bebi","trabalhar → trabalhei","visitar → visitei","ficar → fiquei","comprar → comprei"],
        },
      ],
    },
    {
      id: "d16-speaking",
      lessonDay: 16,
      type: "speaking",
      estimatedMinutes: 15,
      items: [
        { id: "c-ontem-trabalhei", type: "chunk", portuguese: "Ontem trabalhei.", dutch: "Gisteren heb ik gewerkt.", dayIntroduced: 16, category: "wat-deed-je-gisteren", priority: 2 },
        { id: "c-ontem-fui-ao-centro", type: "chunk", portuguese: "Ontem fui ao centro.", dutch: "Gisteren ging ik naar het centrum.", dayIntroduced: 16, category: "wat-deed-je-gisteren", priority: 2 },
        { id: "c-depois-fui-a-um-restaurante", type: "chunk", portuguese: "Depois fui a um restaurante.", dutch: "Daarna ging ik naar een restaurant.", dayIntroduced: 16, category: "wat-deed-je-gisteren", priority: 2 },
        { id: "c-comi-peixe", type: "chunk", portuguese: "Comi peixe.", dutch: "Ik at vis.", dayIntroduced: 16, category: "wat-deed-je-gisteren", priority: 2 },
        { id: "c-bebi-vinho", type: "chunk", portuguese: "Bebi vinho.", dutch: "Ik dronk wijn.", dayIntroduced: 16, category: "wat-deed-je-gisteren", priority: 2 },
      ],
      tasks: [
        {
          title: "Spreekopdracht",
          kind: "speaking",
          body: ["Vertel één minuut wat je gisteren hebt gedaan."],
          steps: [],
        },
      ],
    },
  ],
};
