// Generated by scripts/build-content.mjs — do not edit by hand.
// Source: content/lessons/*.md

import type { LessonDay } from '@/types';

export const day20: LessonDay = {
  day: 20,
  title: "Verleden + heden + toekomst",
  goal: "verschillende tijdsmomenten in één gesprek combineren.",
  checkpoint: true,
  challengeId: "ontem-hoje-amanha",
  modules: [
    {
      id: "d20-vocabulary",
      lessonDay: 20,
      type: "vocabulary",
      estimatedMinutes: 8,
      items: [
        { id: "w-ontem", type: "word", portuguese: "ontem", dutch: "gisteren", dayIntroduced: 16, category: "wat-deed-je-gisteren", priority: 1 },
        { id: "w-hoje", type: "word", portuguese: "hoje", dutch: "vandaag", dayIntroduced: 3, category: "hoe-gaat-het", priority: 1 },
        { id: "w-amanha", type: "word", portuguese: "amanhã", dutch: "morgen", dayIntroduced: 18, category: "morgen-en-de-toekomst", priority: 1 },
        { id: "w-agora", type: "word", portuguese: "agora", dutch: "nu", dayIntroduced: 5, category: "getallen-geld-tijd", priority: 1 },
        { id: "w-antes", type: "word", portuguese: "antes", dutch: "voorheen / ervoor", dayIntroduced: 20, category: "verleden-heden-toekomst", priority: 1 },
        { id: "w-depois", type: "word", portuguese: "depois", dutch: "daarna", dayIntroduced: 16, category: "wat-deed-je-gisteren", priority: 1 },
        { id: "w-ja", type: "word", portuguese: "já", dutch: "al", dayIntroduced: 20, category: "verleden-heden-toekomst", priority: 1 },
        { id: "w-ainda", type: "word", portuguese: "ainda", dutch: "nog", dayIntroduced: 20, category: "verleden-heden-toekomst", priority: 1 },
        { id: "w-esta-semana", type: "word", portuguese: "esta semana", dutch: "deze week", dayIntroduced: 20, category: "verleden-heden-toekomst", priority: 1 },
        { id: "w-na-semana-passada", type: "word", portuguese: "na semana passada", dutch: "vorige week", dayIntroduced: 20, category: "verleden-heden-toekomst", priority: 1 },
        { id: "w-na-proxima-semana", type: "word", portuguese: "na próxima semana", dutch: "volgende week", dayIntroduced: 20, category: "verleden-heden-toekomst", priority: 1 },
      ],
    },
    {
      id: "d20-speaking",
      lessonDay: 20,
      type: "speaking",
      estimatedMinutes: 15,
      items: [],
      tasks: [
        {
          title: "Hoofdopdracht",
          kind: "speaking",
          body: ["Vertel drie korte verhalen:"],
          steps: ["Ontem… — wat deed je gisteren?","Hoje… — wat doe je vandaag?","Amanhã… — wat ga je morgen doen?"],
        },
        {
          title: "Checkpoint — Ontem, Hoje, Amanhã",
          kind: "challenge",
          body: ["Vragen:","Doel: 2–3 minuten zelfstandig spreken met vervolgvragen."],
          steps: ["O que fizeste ontem?","O que estás a fazer hoje?","O que vais fazer amanhã?"],
        },
      ],
    },
  ],
};
