// Generated by scripts/build-content.mjs — do not edit by hand.
// Source: content/lessons/*.md

import type { LessonDay } from '@/types';

export const day08: LessonDay = {
  day: 8,
  title: "Hobby's & vrije tijd",
  goal: "vertellen wat je graag doet en naar interesses vragen.",
  checkpoint: false,
  modules: [
    {
      id: "d08-vocabulary",
      lessonDay: 8,
      type: "vocabulary",
      estimatedMinutes: 8,
      items: [
        { id: "w-gostar-de", type: "word", portuguese: "gostar de", dutch: "houden van / leuk vinden", dayIntroduced: 8, category: "hobby-s-vrije-tijd", priority: 1 },
        { id: "w-adorar", type: "word", portuguese: "adorar", dutch: "dol zijn op", dayIntroduced: 8, category: "hobby-s-vrije-tijd", priority: 1 },
        { id: "w-fazer", type: "word", portuguese: "fazer", dutch: "doen", dayIntroduced: 7, category: "werk-beroep", priority: 1 },
        { id: "w-viajar", type: "word", portuguese: "viajar", dutch: "reizen", dayIntroduced: 8, category: "hobby-s-vrije-tijd", priority: 1 },
        { id: "w-cozinhar", type: "word", portuguese: "cozinhar", dutch: "koken", dayIntroduced: 8, category: "hobby-s-vrije-tijd", priority: 1 },
        { id: "w-comer", type: "word", portuguese: "comer", dutch: "eten", dayIntroduced: 4, category: "in-een-cafe-bestellen", priority: 1 },
        { id: "w-beber", type: "word", portuguese: "beber", dutch: "drinken", dayIntroduced: 4, category: "in-een-cafe-bestellen", priority: 1 },
        { id: "w-ler", type: "word", portuguese: "ler", dutch: "lezen", dayIntroduced: 8, category: "hobby-s-vrije-tijd", priority: 1 },
        { id: "w-ouvir", type: "word", portuguese: "ouvir", dutch: "luisteren", dayIntroduced: 8, category: "hobby-s-vrije-tijd", priority: 1 },
        { id: "w-musica", type: "word", portuguese: "música", dutch: "muziek", dayIntroduced: 8, category: "hobby-s-vrije-tijd", priority: 1 },
        { id: "w-filme", type: "word", portuguese: "filme", dutch: "film", dayIntroduced: 8, category: "hobby-s-vrije-tijd", priority: 1 },
        { id: "w-desporto", type: "word", portuguese: "desporto", dutch: "sport", dayIntroduced: 8, category: "hobby-s-vrije-tijd", priority: 1 },
        { id: "w-futebol", type: "word", portuguese: "futebol", dutch: "voetbal", dayIntroduced: 8, category: "hobby-s-vrije-tijd", priority: 1 },
        { id: "w-bicicleta", type: "word", portuguese: "bicicleta", dutch: "fiets", dayIntroduced: 8, category: "hobby-s-vrije-tijd", priority: 1 },
        { id: "w-tempo-livre", type: "word", portuguese: "tempo livre", dutch: "vrije tijd", dayIntroduced: 8, category: "hobby-s-vrije-tijd", priority: 1 },
      ],
    },
    {
      id: "d08-chunks",
      lessonDay: 8,
      type: "chunks",
      estimatedMinutes: 7,
      items: [
        { id: "c-o-que-gostas-de-fazer", type: "chunk", portuguese: "O que gostas de fazer?", dutch: "Wat doe je graag?", dayIntroduced: 8, category: "hobby-s-vrije-tijd", priority: 2 },
        { id: "c-gosto-de-viajar", type: "chunk", portuguese: "Gosto de viajar.", dutch: "Ik hou van reizen.", dayIntroduced: 8, category: "hobby-s-vrije-tijd", priority: 2 },
        { id: "c-gosto-muito-de-cozinhar", type: "chunk", portuguese: "Gosto muito de cozinhar.", dutch: "Ik kook erg graag.", dayIntroduced: 8, category: "hobby-s-vrije-tijd", priority: 2 },
        { id: "c-gosto-de-ouvir-musica", type: "chunk", portuguese: "Gosto de ouvir música.", dutch: "Ik luister graag naar muziek.", dayIntroduced: 8, category: "hobby-s-vrije-tijd", priority: 2 },
        { id: "c-tambem-gosto-de-vinho", type: "chunk", portuguese: "Também gosto de vinho.", dutch: "Ik hou ook van wijn.", dayIntroduced: 8, category: "hobby-s-vrije-tijd", priority: 2 },
        { id: "c-nao-gosto-muito-de", type: "chunk", portuguese: "Não gosto muito de…", dutch: "Ik hou niet zo van…", dayIntroduced: 8, category: "hobby-s-vrije-tijd", priority: 2 },
        { id: "c-no-meu-tempo-livre", type: "chunk", portuguese: "No meu tempo livre…", dutch: "In mijn vrije tijd…", dayIntroduced: 8, category: "hobby-s-vrije-tijd", priority: 2 },
        { id: "c-e-tu-de-que-gostas", type: "chunk", portuguese: "E tu? De que gostas?", dutch: "En jij? Waar hou jij van?", dayIntroduced: 8, category: "hobby-s-vrije-tijd", priority: 2 },
      ],
    },
    {
      id: "d08-grammar",
      lessonDay: 8,
      type: "grammar",
      estimatedMinutes: 5,
      items: [],
      notes: [
        {
          title: "Grammatica",
          body: ["gostar de + zelfstandig naamwoord / infinitief."],
          points: [],
        },
      ],
    },
    {
      id: "d08-speaking",
      lessonDay: 8,
      type: "speaking",
      estimatedMinutes: 15,
      items: [],
      tasks: [
        {
          title: "Spreekopdracht",
          kind: "speaking",
          body: ["Noem vijf dingen die je leuk vindt en twee die je minder leuk vindt."],
          steps: [],
        },
      ],
    },
  ],
};
