// Generated by scripts/build-content.mjs — do not edit by hand.
// Source: content/lessons/*.md

import type { LessonDay } from '@/types';

export const day03: LessonDay = {
  day: 3,
  title: "Hoe gaat het?",
  goal: "vragen hoe iemand zich voelt en vertellen hoe het met jou gaat.",
  checkpoint: false,
  modules: [
    {
      id: "d03-vocabulary",
      lessonDay: 3,
      type: "vocabulary",
      estimatedMinutes: 8,
      items: [
        { id: "w-estar", type: "word", portuguese: "estar", dutch: "zijn / zich bevinden", dayIntroduced: 3, category: "hoe-gaat-het", priority: 1 },
        { id: "w-bem", type: "word", portuguese: "bem", dutch: "goed", dayIntroduced: 3, category: "hoe-gaat-het", priority: 1 },
        { id: "w-mal", type: "word", portuguese: "mal", dutch: "slecht", dayIntroduced: 3, category: "hoe-gaat-het", priority: 1 },
        { id: "w-muito", type: "word", portuguese: "muito", dutch: "erg / veel", dayIntroduced: 3, category: "hoe-gaat-het", priority: 1 },
        { id: "w-hoje", type: "word", portuguese: "hoje", dutch: "vandaag", dayIntroduced: 3, category: "hoe-gaat-het", priority: 1 },
        { id: "w-cansado", type: "word", portuguese: "cansado", dutch: "moe", dayIntroduced: 3, category: "hoe-gaat-het", priority: 1 },
        { id: "w-contente", type: "word", portuguese: "contente", dutch: "blij / tevreden", dayIntroduced: 3, category: "hoe-gaat-het", priority: 1 },
        { id: "w-ocupado", type: "word", portuguese: "ocupado", dutch: "druk / bezet", dayIntroduced: 3, category: "hoe-gaat-het", priority: 1 },
        { id: "w-tranquilo", type: "word", portuguese: "tranquilo", dutch: "rustig", dayIntroduced: 3, category: "hoe-gaat-het", priority: 1 },
        { id: "w-otimo", type: "word", portuguese: "ótimo", dutch: "uitstekend", dayIntroduced: 3, category: "hoe-gaat-het", priority: 1 },
        { id: "w-assim-assim", type: "word", portuguese: "assim-assim", dutch: "zo-zo", dayIntroduced: 3, category: "hoe-gaat-het", priority: 1 },
        { id: "w-fome", type: "word", portuguese: "fome", dutch: "honger", dayIntroduced: 3, category: "hoe-gaat-het", priority: 1 },
        { id: "w-sede", type: "word", portuguese: "sede", dutch: "dorst", dayIntroduced: 3, category: "hoe-gaat-het", priority: 1 },
        { id: "w-frio", type: "word", portuguese: "frio", dutch: "kou", dayIntroduced: 3, category: "hoe-gaat-het", priority: 1 },
        { id: "w-calor", type: "word", portuguese: "calor", dutch: "warmte", dayIntroduced: 3, category: "hoe-gaat-het", priority: 1 },
      ],
    },
    {
      id: "d03-chunks",
      lessonDay: 3,
      type: "chunks",
      estimatedMinutes: 7,
      items: [
        { id: "c-tudo-bem", type: "chunk", portuguese: "Tudo bem?", dutch: "Alles goed?", dayIntroduced: 3, category: "hoe-gaat-het", priority: 2 },
        { id: "c-como-estas", type: "chunk", portuguese: "Como estás?", dutch: "Hoe gaat het met je?", dayIntroduced: 3, category: "hoe-gaat-het", priority: 2 },
        { id: "c-estou-bem-obrigado", type: "chunk", portuguese: "Estou bem, obrigado.", dutch: "Het gaat goed, bedankt.", dayIntroduced: 3, category: "hoe-gaat-het", priority: 2 },
        { id: "c-estou-muito-bem", type: "chunk", portuguese: "Estou muito bem.", dutch: "Het gaat heel goed.", dayIntroduced: 3, category: "hoe-gaat-het", priority: 2 },
        { id: "c-hoje-estou-cansado", type: "chunk", portuguese: "Hoje estou cansado.", dutch: "Vandaag ben ik moe.", dayIntroduced: 3, category: "hoe-gaat-het", priority: 2 },
        { id: "c-tenho-fome", type: "chunk", portuguese: "Tenho fome.", dutch: "Ik heb honger.", dayIntroduced: 3, category: "hoe-gaat-het", priority: 2 },
        { id: "c-tenho-sede", type: "chunk", portuguese: "Tenho sede.", dutch: "Ik heb dorst.", dayIntroduced: 3, category: "hoe-gaat-het", priority: 2 },
        { id: "c-e-contigo", type: "chunk", portuguese: "E contigo?", dutch: "En met jou?", dayIntroduced: 3, category: "hoe-gaat-het", priority: 2 },
      ],
    },
    {
      id: "d03-listening",
      lessonDay: 3,
      type: "listening",
      estimatedMinutes: 10,
      items: [
        { id: "c-tudo-bem", type: "chunk", portuguese: "Tudo bem?", dutch: "Alles goed?", dayIntroduced: 3, category: "hoe-gaat-het", priority: 2 },
        { id: "c-como-estas", type: "chunk", portuguese: "Como estás?", dutch: "Hoe gaat het met je?", dayIntroduced: 3, category: "hoe-gaat-het", priority: 2 },
        { id: "c-estou-bem-obrigado", type: "chunk", portuguese: "Estou bem, obrigado.", dutch: "Het gaat goed, bedankt.", dayIntroduced: 3, category: "hoe-gaat-het", priority: 2 },
        { id: "c-estou-muito-bem", type: "chunk", portuguese: "Estou muito bem.", dutch: "Het gaat heel goed.", dayIntroduced: 3, category: "hoe-gaat-het", priority: 2 },
        { id: "c-hoje-estou-cansado", type: "chunk", portuguese: "Hoje estou cansado.", dutch: "Vandaag ben ik moe.", dayIntroduced: 3, category: "hoe-gaat-het", priority: 2 },
        { id: "c-tenho-fome", type: "chunk", portuguese: "Tenho fome.", dutch: "Ik heb honger.", dayIntroduced: 3, category: "hoe-gaat-het", priority: 2 },
      ],
    },
    {
      id: "d03-grammar",
      lessonDay: 3,
      type: "grammar",
      estimatedMinutes: 5,
      items: [],
      notes: [
        {
          title: "Grammatica",
          body: ["Eenvoudige vuistregel:"],
          points: ["ser → identiteit / wat iets is","estar → tijdelijke toestand / hoe iets nu is"],
        },
      ],
    },
    {
      id: "d03-speaking",
      lessonDay: 3,
      type: "speaking",
      estimatedMinutes: 15,
      items: [
        { id: "c-tudo-bem", type: "chunk", portuguese: "Tudo bem?", dutch: "Alles goed?", dayIntroduced: 3, category: "hoe-gaat-het", priority: 2 },
        { id: "c-como-estas", type: "chunk", portuguese: "Como estás?", dutch: "Hoe gaat het met je?", dayIntroduced: 3, category: "hoe-gaat-het", priority: 2 },
        { id: "c-estou-bem-obrigado", type: "chunk", portuguese: "Estou bem, obrigado.", dutch: "Het gaat goed, bedankt.", dayIntroduced: 3, category: "hoe-gaat-het", priority: 2 },
        { id: "c-estou-muito-bem", type: "chunk", portuguese: "Estou muito bem.", dutch: "Het gaat heel goed.", dayIntroduced: 3, category: "hoe-gaat-het", priority: 2 },
        { id: "c-hoje-estou-cansado", type: "chunk", portuguese: "Hoje estou cansado.", dutch: "Vandaag ben ik moe.", dayIntroduced: 3, category: "hoe-gaat-het", priority: 2 },
      ],
      tasks: [
        {
          title: "Spreekopdracht",
          kind: "speaking",
          body: ["Vertel hoe je je vandaag voelt en stel minstens één wedervraag."],
          steps: [],
        },
      ],
    },
    {
      id: "d03-test",
      lessonDay: 3,
      type: "test",
      estimatedMinutes: 5,
      items: [
        { id: "c-tudo-bem", type: "chunk", portuguese: "Tudo bem?", dutch: "Alles goed?", dayIntroduced: 3, category: "hoe-gaat-het", priority: 2 },
        { id: "c-como-estas", type: "chunk", portuguese: "Como estás?", dutch: "Hoe gaat het met je?", dayIntroduced: 3, category: "hoe-gaat-het", priority: 2 },
        { id: "c-estou-bem-obrigado", type: "chunk", portuguese: "Estou bem, obrigado.", dutch: "Het gaat goed, bedankt.", dayIntroduced: 3, category: "hoe-gaat-het", priority: 2 },
        { id: "c-estou-muito-bem", type: "chunk", portuguese: "Estou muito bem.", dutch: "Het gaat heel goed.", dayIntroduced: 3, category: "hoe-gaat-het", priority: 2 },
        { id: "c-hoje-estou-cansado", type: "chunk", portuguese: "Hoje estou cansado.", dutch: "Vandaag ben ik moe.", dayIntroduced: 3, category: "hoe-gaat-het", priority: 2 },
        { id: "w-estar", type: "word", portuguese: "estar", dutch: "zijn / zich bevinden", dayIntroduced: 3, category: "hoe-gaat-het", priority: 1 },
        { id: "w-bem", type: "word", portuguese: "bem", dutch: "goed", dayIntroduced: 3, category: "hoe-gaat-het", priority: 1 },
        { id: "w-mal", type: "word", portuguese: "mal", dutch: "slecht", dayIntroduced: 3, category: "hoe-gaat-het", priority: 1 },
        { id: "w-muito", type: "word", portuguese: "muito", dutch: "erg / veel", dayIntroduced: 3, category: "hoe-gaat-het", priority: 1 },
        { id: "w-hoje", type: "word", portuguese: "hoje", dutch: "vandaag", dayIntroduced: 3, category: "hoe-gaat-het", priority: 1 },
      ],
    },
  ],
};
