// Generated by scripts/build-content.mjs — do not edit by hand.
// Source: content/lessons/*.md

import type { LessonDay } from '@/types';

export const day13: LessonDay = {
  day: 13,
  title: "De weg vragen",
  goal: "een locatie vinden en eenvoudige routeaanwijzingen begrijpen.",
  checkpoint: false,
  modules: [
    {
      id: "d13-vocabulary",
      lessonDay: 13,
      type: "vocabulary",
      estimatedMinutes: 8,
      items: [
        { id: "w-esquerda", type: "word", portuguese: "esquerda", dutch: "links", dayIntroduced: 13, category: "de-weg-vragen", priority: 1 },
        { id: "w-direita", type: "word", portuguese: "direita", dutch: "rechts", dayIntroduced: 13, category: "de-weg-vragen", priority: 1 },
        { id: "w-em-frente", type: "word", portuguese: "em frente", dutch: "rechtdoor", dayIntroduced: 13, category: "de-weg-vragen", priority: 1 },
        { id: "w-perto", type: "word", portuguese: "perto", dutch: "dichtbij", dayIntroduced: 13, category: "de-weg-vragen", priority: 1 },
        { id: "w-longe", type: "word", portuguese: "longe", dutch: "ver weg", dayIntroduced: 13, category: "de-weg-vragen", priority: 1 },
        { id: "w-rua", type: "word", portuguese: "rua", dutch: "straat", dayIntroduced: 13, category: "de-weg-vragen", priority: 1 },
        { id: "w-praca", type: "word", portuguese: "praça", dutch: "plein", dayIntroduced: 13, category: "de-weg-vragen", priority: 1 },
        { id: "w-esquina", type: "word", portuguese: "esquina", dutch: "hoek", dayIntroduced: 13, category: "de-weg-vragen", priority: 1 },
        { id: "w-centro", type: "word", portuguese: "centro", dutch: "centrum", dayIntroduced: 13, category: "de-weg-vragen", priority: 1 },
        { id: "w-aqui", type: "word", portuguese: "aqui", dutch: "hier", dayIntroduced: 13, category: "de-weg-vragen", priority: 1 },
        { id: "w-ali", type: "word", portuguese: "ali", dutch: "daar", dayIntroduced: 13, category: "de-weg-vragen", priority: 1 },
        { id: "w-virar", type: "word", portuguese: "virar", dutch: "afslaan", dayIntroduced: 13, category: "de-weg-vragen", priority: 1 },
        { id: "w-seguir", type: "word", portuguese: "seguir", dutch: "volgen / doorgaan", dayIntroduced: 13, category: "de-weg-vragen", priority: 1 },
        { id: "w-atravessar", type: "word", portuguese: "atravessar", dutch: "oversteken", dayIntroduced: 13, category: "de-weg-vragen", priority: 1 },
        { id: "w-mapa", type: "word", portuguese: "mapa", dutch: "kaart", dayIntroduced: 13, category: "de-weg-vragen", priority: 1 },
      ],
    },
    {
      id: "d13-chunks",
      lessonDay: 13,
      type: "chunks",
      estimatedMinutes: 7,
      items: [
        { id: "c-onde-fica", type: "chunk", portuguese: "Onde fica…?", dutch: "Waar is…?", dayIntroduced: 13, category: "de-weg-vragen", priority: 2 },
        { id: "c-como-posso-chegar-ao-centro", type: "chunk", portuguese: "Como posso chegar ao centro?", dutch: "Hoe kom ik in het centrum?", dayIntroduced: 13, category: "de-weg-vragen", priority: 2 },
        { id: "c-e-longe-daqui", type: "chunk", portuguese: "É longe daqui?", dutch: "Is het ver hiervandaan?", dayIntroduced: 13, category: "de-weg-vragen", priority: 2 },
        { id: "c-e-perto", type: "chunk", portuguese: "É perto.", dutch: "Het is dichtbij.", dayIntroduced: 13, category: "de-weg-vragen", priority: 2 },
        { id: "c-a-esquerda", type: "chunk", portuguese: "À esquerda.", dutch: "Naar links.", dayIntroduced: 13, category: "de-weg-vragen", priority: 2 },
        { id: "c-a-direita", type: "chunk", portuguese: "À direita.", dutch: "Naar rechts.", dayIntroduced: 13, category: "de-weg-vragen", priority: 2 },
        { id: "c-sempre-em-frente", type: "chunk", portuguese: "Sempre em frente.", dutch: "Steeds rechtdoor.", dayIntroduced: 13, category: "de-weg-vragen", priority: 2 },
        { id: "c-pode-mostrar-me-no-mapa", type: "chunk", portuguese: "Pode mostrar-me no mapa?", dutch: "Kunt u het op de kaart laten zien?", dayIntroduced: 13, category: "de-weg-vragen", priority: 2 },
      ],
    },
    {
      id: "d13-listening",
      lessonDay: 13,
      type: "listening",
      estimatedMinutes: 10,
      items: [
        { id: "c-onde-fica", type: "chunk", portuguese: "Onde fica…?", dutch: "Waar is…?", dayIntroduced: 13, category: "de-weg-vragen", priority: 2 },
        { id: "c-como-posso-chegar-ao-centro", type: "chunk", portuguese: "Como posso chegar ao centro?", dutch: "Hoe kom ik in het centrum?", dayIntroduced: 13, category: "de-weg-vragen", priority: 2 },
        { id: "c-e-longe-daqui", type: "chunk", portuguese: "É longe daqui?", dutch: "Is het ver hiervandaan?", dayIntroduced: 13, category: "de-weg-vragen", priority: 2 },
        { id: "c-e-perto", type: "chunk", portuguese: "É perto.", dutch: "Het is dichtbij.", dayIntroduced: 13, category: "de-weg-vragen", priority: 2 },
        { id: "c-a-esquerda", type: "chunk", portuguese: "À esquerda.", dutch: "Naar links.", dayIntroduced: 13, category: "de-weg-vragen", priority: 2 },
        { id: "c-a-direita", type: "chunk", portuguese: "À direita.", dutch: "Naar rechts.", dayIntroduced: 13, category: "de-weg-vragen", priority: 2 },
      ],
      notes: [
        {
          title: "Luisterfocus",
          body: ["Herken snel woorden als direita, esquerda, em frente, segunda rua, perto, longe."],
          points: [],
        },
      ],
    },
    {
      id: "d13-speaking",
      lessonDay: 13,
      type: "speaking",
      estimatedMinutes: 15,
      items: [
        { id: "c-onde-fica", type: "chunk", portuguese: "Onde fica…?", dutch: "Waar is…?", dayIntroduced: 13, category: "de-weg-vragen", priority: 2 },
        { id: "c-como-posso-chegar-ao-centro", type: "chunk", portuguese: "Como posso chegar ao centro?", dutch: "Hoe kom ik in het centrum?", dayIntroduced: 13, category: "de-weg-vragen", priority: 2 },
        { id: "c-e-longe-daqui", type: "chunk", portuguese: "É longe daqui?", dutch: "Is het ver hiervandaan?", dayIntroduced: 13, category: "de-weg-vragen", priority: 2 },
        { id: "c-e-perto", type: "chunk", portuguese: "É perto.", dutch: "Het is dichtbij.", dayIntroduced: 13, category: "de-weg-vragen", priority: 2 },
        { id: "c-a-esquerda", type: "chunk", portuguese: "À esquerda.", dutch: "Naar links.", dayIntroduced: 13, category: "de-weg-vragen", priority: 2 },
      ],
      tasks: [
        {
          title: "Spreekopdracht",
          kind: "speaking",
          body: ["Vraag de route naar drie locaties en herhaal de kern van de instructie."],
          steps: [],
        },
      ],
    },
    {
      id: "d13-test",
      lessonDay: 13,
      type: "test",
      estimatedMinutes: 5,
      items: [
        { id: "c-onde-fica", type: "chunk", portuguese: "Onde fica…?", dutch: "Waar is…?", dayIntroduced: 13, category: "de-weg-vragen", priority: 2 },
        { id: "c-como-posso-chegar-ao-centro", type: "chunk", portuguese: "Como posso chegar ao centro?", dutch: "Hoe kom ik in het centrum?", dayIntroduced: 13, category: "de-weg-vragen", priority: 2 },
        { id: "c-e-longe-daqui", type: "chunk", portuguese: "É longe daqui?", dutch: "Is het ver hiervandaan?", dayIntroduced: 13, category: "de-weg-vragen", priority: 2 },
        { id: "c-e-perto", type: "chunk", portuguese: "É perto.", dutch: "Het is dichtbij.", dayIntroduced: 13, category: "de-weg-vragen", priority: 2 },
        { id: "c-a-esquerda", type: "chunk", portuguese: "À esquerda.", dutch: "Naar links.", dayIntroduced: 13, category: "de-weg-vragen", priority: 2 },
        { id: "w-esquerda", type: "word", portuguese: "esquerda", dutch: "links", dayIntroduced: 13, category: "de-weg-vragen", priority: 1 },
        { id: "w-direita", type: "word", portuguese: "direita", dutch: "rechts", dayIntroduced: 13, category: "de-weg-vragen", priority: 1 },
        { id: "w-em-frente", type: "word", portuguese: "em frente", dutch: "rechtdoor", dayIntroduced: 13, category: "de-weg-vragen", priority: 1 },
        { id: "w-perto", type: "word", portuguese: "perto", dutch: "dichtbij", dayIntroduced: 13, category: "de-weg-vragen", priority: 1 },
        { id: "w-longe", type: "word", portuguese: "longe", dutch: "ver weg", dayIntroduced: 13, category: "de-weg-vragen", priority: 1 },
      ],
    },
  ],
};
