// Generated by scripts/build-content.mjs — do not edit by hand.
// Source: content/lessons/*.md

import type { LessonDay } from '@/types';

export const day06: LessonDay = {
  day: 6,
  title: "Familie, partner & vrienden",
  goal: "eenvoudig vertellen wie belangrijke mensen in je leven zijn.",
  checkpoint: false,
  modules: [
    {
      id: "d06-vocabulary",
      lessonDay: 6,
      type: "vocabulary",
      estimatedMinutes: 8,
      items: [
        { id: "w-familia", type: "word", portuguese: "família", dutch: "familie", dayIntroduced: 6, category: "familie-partner-vrienden", priority: 1 },
        { id: "w-amigo-amiga", type: "word", portuguese: "amigo / amiga", dutch: "vriend / vriendin", dayIntroduced: 6, category: "familie-partner-vrienden", priority: 1 },
        { id: "w-namorado-namorada", type: "word", portuguese: "namorado / namorada", dutch: "vriend / vriendin / partner", dayIntroduced: 6, category: "familie-partner-vrienden", priority: 1 },
        { id: "w-pai", type: "word", portuguese: "pai", dutch: "vader", dayIntroduced: 6, category: "familie-partner-vrienden", priority: 1 },
        { id: "w-mae", type: "word", portuguese: "mãe", dutch: "moeder", dayIntroduced: 6, category: "familie-partner-vrienden", priority: 1 },
        { id: "w-irmao", type: "word", portuguese: "irmão", dutch: "broer", dayIntroduced: 6, category: "familie-partner-vrienden", priority: 1 },
        { id: "w-irma", type: "word", portuguese: "irmã", dutch: "zus", dayIntroduced: 6, category: "familie-partner-vrienden", priority: 1 },
        { id: "w-pais", type: "word", portuguese: "pais", dutch: "ouders", dayIntroduced: 2, category: "persoonlijke-informatie", priority: 1 },
        { id: "w-filho-filha", type: "word", portuguese: "filho / filha", dutch: "zoon / dochter", dayIntroduced: 6, category: "familie-partner-vrienden", priority: 1 },
        { id: "w-marido", type: "word", portuguese: "marido", dutch: "echtgenoot", dayIntroduced: 6, category: "familie-partner-vrienden", priority: 1 },
        { id: "w-mulher", type: "word", portuguese: "mulher", dutch: "vrouw / echtgenote", dayIntroduced: 6, category: "familie-partner-vrienden", priority: 1 },
        { id: "w-pessoas", type: "word", portuguese: "pessoas", dutch: "mensen", dayIntroduced: 6, category: "familie-partner-vrienden", priority: 1 },
        { id: "w-meu-minha", type: "word", portuguese: "meu / minha", dutch: "mijn", dayIntroduced: 6, category: "familie-partner-vrienden", priority: 1 },
        { id: "w-teu-tua", type: "word", portuguese: "teu / tua", dutch: "jouw", dayIntroduced: 6, category: "familie-partner-vrienden", priority: 1 },
        { id: "w-com", type: "word", portuguese: "com", dutch: "met", dayIntroduced: 6, category: "familie-partner-vrienden", priority: 1 },
      ],
    },
    {
      id: "d06-chunks",
      lessonDay: 6,
      type: "chunks",
      estimatedMinutes: 7,
      items: [
        { id: "c-tenho-um-irmao", type: "chunk", portuguese: "Tenho um irmão.", dutch: "Ik heb een broer.", dayIntroduced: 6, category: "familie-partner-vrienden", priority: 2 },
        { id: "c-tenho-uma-irma", type: "chunk", portuguese: "Tenho uma irmã.", dutch: "Ik heb een zus.", dayIntroduced: 6, category: "familie-partner-vrienden", priority: 2 },
        { id: "c-esta-e-a-minha-familia", type: "chunk", portuguese: "Esta é a minha família.", dutch: "Dit is mijn familie.", dayIntroduced: 6, category: "familie-partner-vrienden", priority: 2 },
        { id: "c-este-e-o-meu-amigo", type: "chunk", portuguese: "Este é o meu amigo.", dutch: "Dit is mijn vriend.", dayIntroduced: 6, category: "familie-partner-vrienden", priority: 2 },
        { id: "c-esta-e-a-minha-namorada", type: "chunk", portuguese: "Esta é a minha namorada.", dutch: "Dit is mijn vriendin.", dayIntroduced: 6, category: "familie-partner-vrienden", priority: 2 },
        { id: "c-moro-com-a-minha-namorada", type: "chunk", portuguese: "Moro com a minha namorada.", dutch: "Ik woon met mijn vriendin.", dayIntroduced: 6, category: "familie-partner-vrienden", priority: 2 },
        { id: "c-tens-irmaos", type: "chunk", portuguese: "Tens irmãos?", dutch: "Heb je broers of zussen?", dayIntroduced: 6, category: "familie-partner-vrienden", priority: 2 },
        { id: "c-e-a-tua-familia", type: "chunk", portuguese: "E a tua família?", dutch: "En jouw familie?", dayIntroduced: 6, category: "familie-partner-vrienden", priority: 2 },
      ],
    },
    {
      id: "d06-grammar",
      lessonDay: 6,
      type: "grammar",
      estimatedMinutes: 5,
      items: [],
      notes: [
        {
          title: "Grammatica",
          body: ["meu/minha en teu/tua volgen het grammaticale geslacht van het zelfstandig naamwoord."],
          points: [],
        },
      ],
    },
    {
      id: "d06-speaking",
      lessonDay: 6,
      type: "speaking",
      estimatedMinutes: 15,
      items: [],
      tasks: [
        {
          title: "Spreekopdracht",
          kind: "speaking",
          body: ["Praat 30–60 seconden over twee of drie mensen."],
          steps: [],
        },
      ],
    },
  ],
};
