// Generated by scripts/build-content.mjs — do not edit by hand.
// Source: content/lessons/*.md

import type { LessonDay } from '@/types';

export const day25: LessonDay = {
  day: 25,
  title: "Smalltalk natuurlijk laten klinken",
  goal: "natuurlijker reageren en een gesprek gaande houden.",
  checkpoint: true,
  challengeId: "night-out",
  modules: [
    {
      id: "d25-chunks",
      lessonDay: 25,
      type: "chunks",
      estimatedMinutes: 7,
      items: [
        { id: "c-a-serio", type: "chunk", portuguese: "A sério?", dutch: "Echt?", dayIntroduced: 25, category: "smalltalk-natuurlijk-laten-klinken", priority: 2 },
        { id: "c-que-giro", type: "chunk", portuguese: "Que giro!", dutch: "Wat leuk!", dayIntroduced: 25, category: "smalltalk-natuurlijk-laten-klinken", priority: 2 },
        { id: "c-que-fixe", type: "chunk", portuguese: "Que fixe!", dutch: "Gaaf!", dayIntroduced: 25, category: "smalltalk-natuurlijk-laten-klinken", priority: 2 },
        { id: "c-que-pena", type: "chunk", portuguese: "Que pena.", dutch: "Wat jammer.", dayIntroduced: 25, category: "smalltalk-natuurlijk-laten-klinken", priority: 2 },
        { id: "c-claro", type: "chunk", portuguese: "Claro.", dutch: "Natuurlijk.", dayIntroduced: 25, category: "smalltalk-natuurlijk-laten-klinken", priority: 2 },
        { id: "c-pois", type: "chunk", portuguese: "Pois.", dutch: "Tja / inderdaad / nou…", dayIntroduced: 25, category: "smalltalk-natuurlijk-laten-klinken", priority: 2 },
        { id: "c-exato", type: "chunk", portuguese: "Exato.", dutch: "Precies.", dayIntroduced: 25, category: "smalltalk-natuurlijk-laten-klinken", priority: 2 },
        { id: "c-tambem-acho", type: "chunk", portuguese: "Também acho.", dutch: "Vind ik ook.", dayIntroduced: 10, category: "meningen-voorkeuren", priority: 2 },
        { id: "c-nao-sei", type: "chunk", portuguese: "Não sei.", dutch: "Geen idee.", dayIntroduced: 25, category: "smalltalk-natuurlijk-laten-klinken", priority: 2 },
        { id: "c-talvez", type: "chunk", portuguese: "Talvez.", dutch: "Misschien.", dayIntroduced: 25, category: "smalltalk-natuurlijk-laten-klinken", priority: 2 },
        { id: "c-depende", type: "chunk", portuguese: "Depende.", dutch: "Hangt ervan af.", dayIntroduced: 10, category: "meningen-voorkeuren", priority: 2 },
        { id: "c-como-assim", type: "chunk", portuguese: "Como assim?", dutch: "Hoe bedoel je?", dayIntroduced: 25, category: "smalltalk-natuurlijk-laten-klinken", priority: 2 },
        { id: "c-porque", type: "chunk", portuguese: "Porquê?", dutch: "Waarom?", dayIntroduced: 25, category: "smalltalk-natuurlijk-laten-klinken", priority: 2 },
        { id: "c-e-entao", type: "chunk", portuguese: "E então?", dutch: "En toen? / En dus?", dayIntroduced: 25, category: "smalltalk-natuurlijk-laten-klinken", priority: 2 },
        { id: "c-e-tu", type: "chunk", portuguese: "E tu?", dutch: "En jij?", dayIntroduced: 2, category: "persoonlijke-informatie", priority: 2 },
      ],
    },
    {
      id: "d25-speaking",
      lessonDay: 25,
      type: "speaking",
      estimatedMinutes: 15,
      items: [],
      tasks: [
        {
          title: "Checkpoint — Night Out in Portugal",
          kind: "challenge",
          body: ["Doel: 8–10 minuten gesprek over:","Regel: geen antwoord mag alleen uit sim of não bestaan."],
          steps: ["jezelf","werk","reizen","eten","verschillen tussen landen","weekendplannen"],
        },
      ],
    },
  ],
};
