// Generated by scripts/build-content.mjs — do not edit by hand.
// Source: content/lessons/*.md

import type { LessonDay } from '@/types';

export const day27: LessonDay = {
  day: 27,
  title: "Eenvoudig zakelijk gesprek",
  goal: "de kern van een simpel werkgesprek bespreken.",
  checkpoint: false,
  modules: [
    {
      id: "d27-vocabulary",
      lessonDay: 27,
      type: "vocabulary",
      estimatedMinutes: 8,
      items: [
        { id: "w-campanha", type: "word", portuguese: "campanha", dutch: "campagne", dayIntroduced: 27, category: "eenvoudig-zakelijk-gesprek", priority: 1 },
        { id: "w-anuncio", type: "word", portuguese: "anúncio", dutch: "advertentie", dayIntroduced: 27, category: "eenvoudig-zakelijk-gesprek", priority: 1 },
        { id: "w-orcamento", type: "word", portuguese: "orçamento", dutch: "budget", dayIntroduced: 27, category: "eenvoudig-zakelijk-gesprek", priority: 1 },
        { id: "w-resultado", type: "word", portuguese: "resultado", dutch: "resultaat", dayIntroduced: 26, category: "zakelijk-kennismaken", priority: 1 },
        { id: "w-venda", type: "word", portuguese: "venda", dutch: "verkoop", dayIntroduced: 27, category: "eenvoudig-zakelijk-gesprek", priority: 1 },
        { id: "w-cliente", type: "word", portuguese: "cliente", dutch: "klant", dayIntroduced: 7, category: "werk-beroep", priority: 1 },
        { id: "w-dados", type: "word", portuguese: "dados", dutch: "data", dayIntroduced: 27, category: "eenvoudig-zakelijk-gesprek", priority: 1 },
        { id: "w-custo", type: "word", portuguese: "custo", dutch: "kosten", dayIntroduced: 27, category: "eenvoudig-zakelijk-gesprek", priority: 1 },
        { id: "w-conversao", type: "word", portuguese: "conversão", dutch: "conversie", dayIntroduced: 27, category: "eenvoudig-zakelijk-gesprek", priority: 1 },
        { id: "w-objetivo", type: "word", portuguese: "objetivo", dutch: "doel", dayIntroduced: 26, category: "zakelijk-kennismaken", priority: 1 },
        { id: "w-melhorar", type: "word", portuguese: "melhorar", dutch: "verbeteren", dayIntroduced: 27, category: "eenvoudig-zakelijk-gesprek", priority: 1 },
        { id: "w-aumentar", type: "word", portuguese: "aumentar", dutch: "verhogen", dayIntroduced: 27, category: "eenvoudig-zakelijk-gesprek", priority: 1 },
        { id: "w-reduzir", type: "word", portuguese: "reduzir", dutch: "verlagen", dayIntroduced: 27, category: "eenvoudig-zakelijk-gesprek", priority: 1 },
        { id: "w-medir", type: "word", portuguese: "medir", dutch: "meten", dayIntroduced: 27, category: "eenvoudig-zakelijk-gesprek", priority: 1 },
        { id: "w-solucao", type: "word", portuguese: "solução", dutch: "oplossing", dayIntroduced: 27, category: "eenvoudig-zakelijk-gesprek", priority: 1 },
      ],
    },
    {
      id: "d27-chunks",
      lessonDay: 27,
      type: "chunks",
      estimatedMinutes: 7,
      items: [
        { id: "c-o-objetivo-e", type: "chunk", portuguese: "O objetivo é…", dutch: "Het doel is…", dayIntroduced: 27, category: "eenvoudig-zakelijk-gesprek", priority: 2 },
        { id: "c-estamos-a-tentar-melhorar-os-resultados", type: "chunk", portuguese: "Estamos a tentar melhorar os resultados.", dutch: "We proberen de resultaten te verbeteren.", dayIntroduced: 27, category: "eenvoudig-zakelijk-gesprek", priority: 2 },
        { id: "c-os-resultados-sao-bons", type: "chunk", portuguese: "Os resultados são bons.", dutch: "De resultaten zijn goed.", dayIntroduced: 27, category: "eenvoudig-zakelijk-gesprek", priority: 2 },
        { id: "c-precisamos-de-melhorar-isto", type: "chunk", portuguese: "Precisamos de melhorar isto.", dutch: "We moeten dit verbeteren.", dayIntroduced: 27, category: "eenvoudig-zakelijk-gesprek", priority: 2 },
        { id: "c-qual-e-o-orcamento", type: "chunk", portuguese: "Qual é o orçamento?", dutch: "Wat is het budget?", dayIntroduced: 27, category: "eenvoudig-zakelijk-gesprek", priority: 2 },
        { id: "c-temos-mais-clientes-este-mes", type: "chunk", portuguese: "Temos mais clientes este mês.", dutch: "We hebben deze maand meer klanten.", dayIntroduced: 27, category: "eenvoudig-zakelijk-gesprek", priority: 2 },
        { id: "c-o-custo-e-demasiado-alto", type: "chunk", portuguese: "O custo é demasiado alto.", dutch: "De kosten zijn te hoog.", dayIntroduced: 27, category: "eenvoudig-zakelijk-gesprek", priority: 2 },
        { id: "c-qual-e-o-proximo-passo", type: "chunk", portuguese: "Qual é o próximo passo?", dutch: "Wat is de volgende stap?", dayIntroduced: 27, category: "eenvoudig-zakelijk-gesprek", priority: 2 },
      ],
    },
    {
      id: "d27-speaking",
      lessonDay: 27,
      type: "speaking",
      estimatedMinutes: 15,
      items: [],
      tasks: [
        {
          title: "Spreekopdracht",
          kind: "speaking",
          body: ["Leg een fictief project uit: doel, huidige situatie, wat goed gaat, wat beter moet en volgende stap."],
          steps: [],
        },
      ],
    },
  ],
};
