// Generated by scripts/build-content.mjs — do not edit by hand.
// Source: content/lessons/*.md

import type { LessonDay } from '@/types';

export const day02: LessonDay = {
  day: 2,
  title: "Persoonlijke informatie",
  goal: "leeftijd, woonplaats, herkomst en talen benoemen en ernaar vragen.",
  checkpoint: false,
  modules: [
    {
      id: "d02-vocabulary",
      lessonDay: 2,
      type: "vocabulary",
      estimatedMinutes: 8,
      items: [
        { id: "w-ter", type: "word", portuguese: "ter", dutch: "hebben", dayIntroduced: 2, category: "persoonlijke-informatie", priority: 1 },
        { id: "w-morar", type: "word", portuguese: "morar", dutch: "wonen", dayIntroduced: 2, category: "persoonlijke-informatie", priority: 1 },
        { id: "w-viver", type: "word", portuguese: "viver", dutch: "leven / wonen", dayIntroduced: 2, category: "persoonlijke-informatie", priority: 1 },
        { id: "w-falar", type: "word", portuguese: "falar", dutch: "spreken", dayIntroduced: 2, category: "persoonlijke-informatie", priority: 1 },
        { id: "w-aprender", type: "word", portuguese: "aprender", dutch: "leren", dayIntroduced: 2, category: "persoonlijke-informatie", priority: 1 },
        { id: "w-anos", type: "word", portuguese: "anos", dutch: "jaren", dayIntroduced: 2, category: "persoonlijke-informatie", priority: 1 },
        { id: "w-idade", type: "word", portuguese: "idade", dutch: "leeftijd", dayIntroduced: 2, category: "persoonlijke-informatie", priority: 1 },
        { id: "w-pais", type: "word", portuguese: "país", dutch: "land", dayIntroduced: 2, category: "persoonlijke-informatie", priority: 1 },
        { id: "w-cidade", type: "word", portuguese: "cidade", dutch: "stad", dayIntroduced: 2, category: "persoonlijke-informatie", priority: 1 },
        { id: "w-lingua", type: "word", portuguese: "língua", dutch: "taal", dayIntroduced: 2, category: "persoonlijke-informatie", priority: 1 },
        { id: "w-neerlandes", type: "word", portuguese: "neerlandês", dutch: "Nederlands", dayIntroduced: 2, category: "persoonlijke-informatie", priority: 1 },
        { id: "w-ingles", type: "word", portuguese: "inglês", dutch: "Engels", dayIntroduced: 2, category: "persoonlijke-informatie", priority: 1 },
        { id: "w-onde", type: "word", portuguese: "onde", dutch: "waar", dayIntroduced: 2, category: "persoonlijke-informatie", priority: 1 },
        { id: "w-quantos", type: "word", portuguese: "quantos", dutch: "hoeveel", dayIntroduced: 2, category: "persoonlijke-informatie", priority: 1 },
        { id: "w-tambem", type: "word", portuguese: "também", dutch: "ook", dayIntroduced: 2, category: "persoonlijke-informatie", priority: 1 },
      ],
    },
    {
      id: "d02-chunks",
      lessonDay: 2,
      type: "chunks",
      estimatedMinutes: 7,
      items: [
        { id: "c-onde-moras", type: "chunk", portuguese: "Onde moras?", dutch: "Waar woon je?", dayIntroduced: 2, category: "persoonlijke-informatie", priority: 2 },
        { id: "c-moro-nos-paises-baixos", type: "chunk", portuguese: "Moro nos Países Baixos.", dutch: "Ik woon in Nederland.", dayIntroduced: 2, category: "persoonlijke-informatie", priority: 2 },
        { id: "c-de-onde-es", type: "chunk", portuguese: "De onde és?", dutch: "Waar kom je vandaan?", dayIntroduced: 2, category: "persoonlijke-informatie", priority: 2 },
        { id: "c-tenho-26-anos", type: "chunk", portuguese: "Tenho 26 anos.", dutch: "Ik ben 26 jaar.", dayIntroduced: 2, category: "persoonlijke-informatie", priority: 2 },
        { id: "c-que-linguas-falas", type: "chunk", portuguese: "Que línguas falas?", dutch: "Welke talen spreek je?", dayIntroduced: 2, category: "persoonlijke-informatie", priority: 2 },
        { id: "c-falo-neerlandes-e-ingles", type: "chunk", portuguese: "Falo neerlandês e inglês.", dutch: "Ik spreek Nederlands en Engels.", dayIntroduced: 2, category: "persoonlijke-informatie", priority: 2 },
        { id: "c-tambem-estou-a-aprender-portugues", type: "chunk", portuguese: "Também estou a aprender português.", dutch: "Ik ben ook Portugees aan het leren.", dayIntroduced: 2, category: "persoonlijke-informatie", priority: 2 },
        { id: "c-e-tu", type: "chunk", portuguese: "E tu?", dutch: "En jij?", dayIntroduced: 2, category: "persoonlijke-informatie", priority: 2 },
      ],
    },
    {
      id: "d02-grammar",
      lessonDay: 2,
      type: "grammar",
      estimatedMinutes: 5,
      items: [],
      notes: [
        {
          title: "Grammatica",
          body: ["Leeftijd wordt uitgedrukt met ter:"],
          points: ["eu tenho","tu tens"],
        },
      ],
    },
    {
      id: "d02-speaking",
      lessonDay: 2,
      type: "speaking",
      estimatedMinutes: 15,
      items: [],
      tasks: [
        {
          title: "Spreekopdracht",
          kind: "speaking",
          body: ["Beantwoord spontaan vragen over leeftijd, woonplaats, land en talen."],
          steps: [],
        },
      ],
    },
  ],
};
