// Generated by scripts/build-content.mjs — do not edit by hand.
// Source: content/lessons/*.md

import type { LessonDay } from '@/types';

export const day09: LessonDay = {
  day: 9,
  title: "Dagelijkse routine",
  goal: "ongeveer één minuut vertellen hoe een normale dag verloopt.",
  checkpoint: false,
  modules: [
    {
      id: "d09-vocabulary",
      lessonDay: 9,
      type: "vocabulary",
      estimatedMinutes: 8,
      items: [
        { id: "w-acordar", type: "word", portuguese: "acordar", dutch: "wakker worden", dayIntroduced: 9, category: "dagelijkse-routine", priority: 1 },
        { id: "w-levantar-se", type: "word", portuguese: "levantar-se", dutch: "opstaan", dayIntroduced: 9, category: "dagelijkse-routine", priority: 1 },
        { id: "w-tomar", type: "word", portuguese: "tomar", dutch: "nemen", dayIntroduced: 9, category: "dagelijkse-routine", priority: 1 },
        { id: "w-pequeno-almoco", type: "word", portuguese: "pequeno-almoço", dutch: "ontbijt", dayIntroduced: 9, category: "dagelijkse-routine", priority: 1 },
        { id: "w-comecar", type: "word", portuguese: "começar", dutch: "beginnen", dayIntroduced: 9, category: "dagelijkse-routine", priority: 1 },
        { id: "w-acabar", type: "word", portuguese: "acabar", dutch: "eindigen", dayIntroduced: 9, category: "dagelijkse-routine", priority: 1 },
        { id: "w-ir", type: "word", portuguese: "ir", dutch: "gaan", dayIntroduced: 9, category: "dagelijkse-routine", priority: 1 },
        { id: "w-casa", type: "word", portuguese: "casa", dutch: "huis", dayIntroduced: 9, category: "dagelijkse-routine", priority: 1 },
        { id: "w-manha", type: "word", portuguese: "manhã", dutch: "ochtend", dayIntroduced: 9, category: "dagelijkse-routine", priority: 1 },
        { id: "w-tarde", type: "word", portuguese: "tarde", dutch: "middag", dayIntroduced: 9, category: "dagelijkse-routine", priority: 1 },
        { id: "w-noite", type: "word", portuguese: "noite", dutch: "avond", dayIntroduced: 9, category: "dagelijkse-routine", priority: 1 },
        { id: "w-normalmente", type: "word", portuguese: "normalmente", dutch: "normaal gesproken", dayIntroduced: 9, category: "dagelijkse-routine", priority: 1 },
        { id: "w-geralmente", type: "word", portuguese: "geralmente", dutch: "meestal", dayIntroduced: 9, category: "dagelijkse-routine", priority: 1 },
        { id: "w-sempre", type: "word", portuguese: "sempre", dutch: "altijd", dayIntroduced: 9, category: "dagelijkse-routine", priority: 1 },
        { id: "w-as-vezes", type: "word", portuguese: "às vezes", dutch: "soms", dayIntroduced: 9, category: "dagelijkse-routine", priority: 1 },
      ],
    },
    {
      id: "d09-chunks",
      lessonDay: 9,
      type: "chunks",
      estimatedMinutes: 7,
      items: [
        { id: "c-normalmente-acordo-as-sete", type: "chunk", portuguese: "Normalmente acordo às sete.", dutch: "Normaal word ik om zeven uur wakker.", dayIntroduced: 9, category: "dagelijkse-routine", priority: 2 },
        { id: "c-tomo-o-pequeno-almoco", type: "chunk", portuguese: "Tomo o pequeno-almoço.", dutch: "Ik ontbijt.", dayIntroduced: 9, category: "dagelijkse-routine", priority: 2 },
        { id: "c-depois-vou-trabalhar", type: "chunk", portuguese: "Depois vou trabalhar.", dutch: "Daarna ga ik werken.", dayIntroduced: 9, category: "dagelijkse-routine", priority: 2 },
        { id: "c-comeco-a-trabalhar-as-nove", type: "chunk", portuguese: "Começo a trabalhar às nove.", dutch: "Ik begin om negen uur met werken.", dayIntroduced: 9, category: "dagelijkse-routine", priority: 2 },
        { id: "c-almoco-ao-meio-dia", type: "chunk", portuguese: "Almoço ao meio-dia.", dutch: "Ik lunch rond het middaguur.", dayIntroduced: 9, category: "dagelijkse-routine", priority: 2 },
        { id: "c-acabo-de-trabalhar-as-cinco", type: "chunk", portuguese: "Acabo de trabalhar às cinco.", dutch: "Ik stop om vijf uur met werken.", dayIntroduced: 9, category: "dagelijkse-routine", priority: 2 },
        { id: "c-a-noite-gosto-de", type: "chunk", portuguese: "À noite gosto de…", dutch: "'s Avonds houd ik ervan om…", dayIntroduced: 9, category: "dagelijkse-routine", priority: 2 },
        { id: "c-depois-vou-para-casa", type: "chunk", portuguese: "Depois vou para casa.", dutch: "Daarna ga ik naar huis.", dayIntroduced: 9, category: "dagelijkse-routine", priority: 2 },
      ],
    },
    {
      id: "d09-listening",
      lessonDay: 9,
      type: "listening",
      estimatedMinutes: 10,
      items: [
        { id: "c-normalmente-acordo-as-sete", type: "chunk", portuguese: "Normalmente acordo às sete.", dutch: "Normaal word ik om zeven uur wakker.", dayIntroduced: 9, category: "dagelijkse-routine", priority: 2 },
        { id: "c-tomo-o-pequeno-almoco", type: "chunk", portuguese: "Tomo o pequeno-almoço.", dutch: "Ik ontbijt.", dayIntroduced: 9, category: "dagelijkse-routine", priority: 2 },
        { id: "c-depois-vou-trabalhar", type: "chunk", portuguese: "Depois vou trabalhar.", dutch: "Daarna ga ik werken.", dayIntroduced: 9, category: "dagelijkse-routine", priority: 2 },
        { id: "c-comeco-a-trabalhar-as-nove", type: "chunk", portuguese: "Começo a trabalhar às nove.", dutch: "Ik begin om negen uur met werken.", dayIntroduced: 9, category: "dagelijkse-routine", priority: 2 },
        { id: "c-almoco-ao-meio-dia", type: "chunk", portuguese: "Almoço ao meio-dia.", dutch: "Ik lunch rond het middaguur.", dayIntroduced: 9, category: "dagelijkse-routine", priority: 2 },
        { id: "c-acabo-de-trabalhar-as-cinco", type: "chunk", portuguese: "Acabo de trabalhar às cinco.", dutch: "Ik stop om vijf uur met werken.", dayIntroduced: 9, category: "dagelijkse-routine", priority: 2 },
      ],
    },
    {
      id: "d09-grammar",
      lessonDay: 9,
      type: "grammar",
      estimatedMinutes: 5,
      items: [],
      notes: [
        {
          title: "Grammatica",
          body: ["Gebruik volgordewoorden zoals primeiro, depois, normalmente, à tarde, à noite."],
          points: [],
        },
      ],
    },
    {
      id: "d09-speaking",
      lessonDay: 9,
      type: "speaking",
      estimatedMinutes: 15,
      items: [
        { id: "c-normalmente-acordo-as-sete", type: "chunk", portuguese: "Normalmente acordo às sete.", dutch: "Normaal word ik om zeven uur wakker.", dayIntroduced: 9, category: "dagelijkse-routine", priority: 2 },
        { id: "c-tomo-o-pequeno-almoco", type: "chunk", portuguese: "Tomo o pequeno-almoço.", dutch: "Ik ontbijt.", dayIntroduced: 9, category: "dagelijkse-routine", priority: 2 },
        { id: "c-depois-vou-trabalhar", type: "chunk", portuguese: "Depois vou trabalhar.", dutch: "Daarna ga ik werken.", dayIntroduced: 9, category: "dagelijkse-routine", priority: 2 },
        { id: "c-comeco-a-trabalhar-as-nove", type: "chunk", portuguese: "Começo a trabalhar às nove.", dutch: "Ik begin om negen uur met werken.", dayIntroduced: 9, category: "dagelijkse-routine", priority: 2 },
        { id: "c-almoco-ao-meio-dia", type: "chunk", portuguese: "Almoço ao meio-dia.", dutch: "Ik lunch rond het middaguur.", dayIntroduced: 9, category: "dagelijkse-routine", priority: 2 },
      ],
      tasks: [
        {
          title: "Spreekopdracht",
          kind: "speaking",
          body: ["Beschrijf minimaal zes stappen van je normale werkdag."],
          steps: [],
        },
      ],
    },
  ],
};
