// Generated by scripts/build-content.mjs — do not edit by hand.
// Source: content/lessons/*.md

import type { LessonDay } from '@/types';

export const day15: LessonDay = {
  day: 15,
  title: "Hotel & problemen begrijpen",
  goal: "inchecken, informatie vragen en een simpel probleem uitleggen.",
  checkpoint: true,
  challengeId: "travel-day",
  modules: [
    {
      id: "d15-vocabulary",
      lessonDay: 15,
      type: "vocabulary",
      estimatedMinutes: 8,
      items: [
        { id: "w-hotel", type: "word", portuguese: "hotel", dutch: "hotel", dayIntroduced: 15, category: "hotel-problemen-begrijpen", priority: 1 },
        { id: "w-reserva", type: "word", portuguese: "reserva", dutch: "reservering", dayIntroduced: 15, category: "hotel-problemen-begrijpen", priority: 1 },
        { id: "w-quarto", type: "word", portuguese: "quarto", dutch: "kamer", dayIntroduced: 15, category: "hotel-problemen-begrijpen", priority: 1 },
        { id: "w-rececao", type: "word", portuguese: "receção", dutch: "receptie", dayIntroduced: 15, category: "hotel-problemen-begrijpen", priority: 1 },
        { id: "w-chave", type: "word", portuguese: "chave", dutch: "sleutel", dayIntroduced: 15, category: "hotel-problemen-begrijpen", priority: 1 },
        { id: "w-andar", type: "word", portuguese: "andar", dutch: "verdieping", dayIntroduced: 15, category: "hotel-problemen-begrijpen", priority: 1 },
        { id: "w-elevador", type: "word", portuguese: "elevador", dutch: "lift", dayIntroduced: 15, category: "hotel-problemen-begrijpen", priority: 1 },
        { id: "w-casa-de-banho", type: "word", portuguese: "casa de banho", dutch: "badkamer / toilet", dayIntroduced: 15, category: "hotel-problemen-begrijpen", priority: 1 },
        { id: "w-toalha", type: "word", portuguese: "toalha", dutch: "handdoek", dayIntroduced: 15, category: "hotel-problemen-begrijpen", priority: 1 },
        { id: "w-pequeno-almoco", type: "word", portuguese: "pequeno-almoço", dutch: "ontbijt", dayIntroduced: 9, category: "dagelijkse-routine", priority: 1 },
        { id: "w-noite", type: "word", portuguese: "noite", dutch: "nacht", dayIntroduced: 9, category: "dagelijkse-routine", priority: 1 },
        { id: "w-problema", type: "word", portuguese: "problema", dutch: "probleem", dayIntroduced: 15, category: "hotel-problemen-begrijpen", priority: 1 },
        { id: "w-funcionar", type: "word", portuguese: "funcionar", dutch: "werken / functioneren", dayIntroduced: 15, category: "hotel-problemen-begrijpen", priority: 1 },
        { id: "w-precisar", type: "word", portuguese: "precisar", dutch: "nodig hebben", dayIntroduced: 15, category: "hotel-problemen-begrijpen", priority: 1 },
        { id: "w-ajudar", type: "word", portuguese: "ajudar", dutch: "helpen", dayIntroduced: 7, category: "werk-beroep", priority: 1 },
      ],
    },
    {
      id: "d15-chunks",
      lessonDay: 15,
      type: "chunks",
      estimatedMinutes: 7,
      items: [
        { id: "c-tenho-uma-reserva", type: "chunk", portuguese: "Tenho uma reserva.", dutch: "Ik heb een reservering.", dayIntroduced: 15, category: "hotel-problemen-begrijpen", priority: 2 },
        { id: "c-em-nome-de-duran", type: "chunk", portuguese: "Em nome de Duran.", dutch: "Op naam van Duran.", dayIntroduced: 15, category: "hotel-problemen-begrijpen", priority: 2 },
        { id: "c-a-que-horas-e-o-pequeno-almoco", type: "chunk", portuguese: "A que horas é o pequeno-almoço?", dutch: "Hoe laat is het ontbijt?", dayIntroduced: 15, category: "hotel-problemen-begrijpen", priority: 2 },
        { id: "c-onde-fica-o-meu-quarto", type: "chunk", portuguese: "Onde fica o meu quarto?", dutch: "Waar is mijn kamer?", dayIntroduced: 15, category: "hotel-problemen-begrijpen", priority: 2 },
        { id: "c-o-wi-fi-nao-funciona", type: "chunk", portuguese: "O Wi-Fi não funciona.", dutch: "De wifi werkt niet.", dayIntroduced: 15, category: "hotel-problemen-begrijpen", priority: 2 },
        { id: "c-preciso-de-uma-toalha", type: "chunk", portuguese: "Preciso de uma toalha.", dutch: "Ik heb een handdoek nodig.", dayIntroduced: 15, category: "hotel-problemen-begrijpen", priority: 2 },
        { id: "c-ha-um-problema-com-o-quarto", type: "chunk", portuguese: "Há um problema com o quarto.", dutch: "Er is een probleem met de kamer.", dayIntroduced: 15, category: "hotel-problemen-begrijpen", priority: 2 },
        { id: "c-pode-ajudar-me-por-favor", type: "chunk", portuguese: "Pode ajudar-me, por favor?", dutch: "Kunt u mij helpen?", dayIntroduced: 15, category: "hotel-problemen-begrijpen", priority: 2 },
        { id: "c-nao-percebo", type: "chunk", portuguese: "Não percebo.", dutch: "Ik begrijp het niet.", dayIntroduced: 15, category: "hotel-problemen-begrijpen", priority: 2 },
        { id: "c-pode-repetir", type: "chunk", portuguese: "Pode repetir?", dutch: "Kunt u het herhalen?", dayIntroduced: 15, category: "hotel-problemen-begrijpen", priority: 2 },
        { id: "c-pode-falar-mais-devagar", type: "chunk", portuguese: "Pode falar mais devagar?", dutch: "Kunt u langzamer spreken?", dayIntroduced: 15, category: "hotel-problemen-begrijpen", priority: 2 },
        { id: "c-pode-dizer-outra-vez", type: "chunk", portuguese: "Pode dizer outra vez?", dutch: "Kunt u het nog een keer zeggen?", dayIntroduced: 15, category: "hotel-problemen-begrijpen", priority: 2 },
        { id: "c-o-que-significa", type: "chunk", portuguese: "O que significa…?", dutch: "Wat betekent…?", dayIntroduced: 15, category: "hotel-problemen-begrijpen", priority: 2 },
        { id: "c-como-se-diz-em-portugues", type: "chunk", portuguese: "Como se diz … em português?", dutch: "Hoe zeg je … in het Portugees?", dayIntroduced: 15, category: "hotel-problemen-begrijpen", priority: 2 },
      ],
    },
    {
      id: "d15-speaking",
      lessonDay: 15,
      type: "speaking",
      estimatedMinutes: 15,
      items: [],
      tasks: [
        {
          title: "Checkpoint — Portugal Travel Day",
          kind: "challenge",
          body: ["Scenario: station → hotel → kamerprobleem → restaurant → betalen.","Doel: ongeveer zeven minuten praktische interactie."],
          steps: [],
        },
      ],
    },
  ],
};
