// Generated by scripts/build-content.mjs — do not edit by hand.
// Source: content/lessons/*.md

import type { LessonDay } from '@/types';

export const day04: LessonDay = {
  day: 4,
  title: "In een café bestellen",
  goal: "zonder Engels een simpele bestelling doen.",
  checkpoint: false,
  modules: [
    {
      id: "d04-vocabulary",
      lessonDay: 4,
      type: "vocabulary",
      estimatedMinutes: 8,
      items: [
        { id: "w-cafe", type: "word", portuguese: "café", dutch: "koffie", dayIntroduced: 4, category: "in-een-cafe-bestellen", priority: 1 },
        { id: "w-agua", type: "word", portuguese: "água", dutch: "water", dayIntroduced: 4, category: "in-een-cafe-bestellen", priority: 1 },
        { id: "w-cerveja", type: "word", portuguese: "cerveja", dutch: "bier", dayIntroduced: 4, category: "in-een-cafe-bestellen", priority: 1 },
        { id: "w-vinho", type: "word", portuguese: "vinho", dutch: "wijn", dayIntroduced: 4, category: "in-een-cafe-bestellen", priority: 1 },
        { id: "w-cha", type: "word", portuguese: "chá", dutch: "thee", dayIntroduced: 4, category: "in-een-cafe-bestellen", priority: 1 },
        { id: "w-leite", type: "word", portuguese: "leite", dutch: "melk", dayIntroduced: 4, category: "in-een-cafe-bestellen", priority: 1 },
        { id: "w-acucar", type: "word", portuguese: "açúcar", dutch: "suiker", dayIntroduced: 4, category: "in-een-cafe-bestellen", priority: 1 },
        { id: "w-garrafa", type: "word", portuguese: "garrafa", dutch: "fles", dayIntroduced: 4, category: "in-een-cafe-bestellen", priority: 1 },
        { id: "w-copo", type: "word", portuguese: "copo", dutch: "glas", dayIntroduced: 4, category: "in-een-cafe-bestellen", priority: 1 },
        { id: "w-chavena", type: "word", portuguese: "chávena", dutch: "kopje", dayIntroduced: 4, category: "in-een-cafe-bestellen", priority: 1 },
        { id: "w-comida", type: "word", portuguese: "comida", dutch: "eten", dayIntroduced: 4, category: "in-een-cafe-bestellen", priority: 1 },
        { id: "w-beber", type: "word", portuguese: "beber", dutch: "drinken", dayIntroduced: 4, category: "in-een-cafe-bestellen", priority: 1 },
        { id: "w-comer", type: "word", portuguese: "comer", dutch: "eten", dayIntroduced: 4, category: "in-een-cafe-bestellen", priority: 1 },
        { id: "w-querer", type: "word", portuguese: "querer", dutch: "willen", dayIntroduced: 4, category: "in-een-cafe-bestellen", priority: 1 },
        { id: "w-mais", type: "word", portuguese: "mais", dutch: "meer / nog", dayIntroduced: 4, category: "in-een-cafe-bestellen", priority: 1 },
      ],
    },
    {
      id: "d04-chunks",
      lessonDay: 4,
      type: "chunks",
      estimatedMinutes: 7,
      items: [
        { id: "c-queria-um-cafe-por-favor", type: "chunk", portuguese: "Queria um café, por favor.", dutch: "Ik zou graag een koffie willen.", dayIntroduced: 4, category: "in-een-cafe-bestellen", priority: 2 },
        { id: "c-queria-uma-cerveja", type: "chunk", portuguese: "Queria uma cerveja.", dutch: "Ik zou graag een bier willen.", dayIntroduced: 4, category: "in-een-cafe-bestellen", priority: 2 },
        { id: "c-uma-agua-por-favor", type: "chunk", portuguese: "Uma água, por favor.", dutch: "Een water, alstublieft.", dayIntroduced: 4, category: "in-een-cafe-bestellen", priority: 2 },
        { id: "c-com-leite-por-favor", type: "chunk", portuguese: "Com leite, por favor.", dutch: "Met melk, alstublieft.", dayIntroduced: 4, category: "in-een-cafe-bestellen", priority: 2 },
        { id: "c-sem-acucar", type: "chunk", portuguese: "Sem açúcar.", dutch: "Zonder suiker.", dayIntroduced: 4, category: "in-een-cafe-bestellen", priority: 2 },
        { id: "c-mais-alguma-coisa", type: "chunk", portuguese: "Mais alguma coisa?", dutch: "Nog iets?", dayIntroduced: 4, category: "in-een-cafe-bestellen", priority: 2 },
        { id: "c-nao-obrigado", type: "chunk", portuguese: "Não, obrigado.", dutch: "Nee, bedankt.", dayIntroduced: 4, category: "in-een-cafe-bestellen", priority: 2 },
        { id: "c-e-tudo-obrigado", type: "chunk", portuguese: "É tudo, obrigado.", dutch: "Dat is alles, bedankt.", dayIntroduced: 4, category: "in-een-cafe-bestellen", priority: 2 },
      ],
    },
    {
      id: "d04-listening",
      lessonDay: 4,
      type: "listening",
      estimatedMinutes: 10,
      items: [
        { id: "c-queria-um-cafe-por-favor", type: "chunk", portuguese: "Queria um café, por favor.", dutch: "Ik zou graag een koffie willen.", dayIntroduced: 4, category: "in-een-cafe-bestellen", priority: 2 },
        { id: "c-queria-uma-cerveja", type: "chunk", portuguese: "Queria uma cerveja.", dutch: "Ik zou graag een bier willen.", dayIntroduced: 4, category: "in-een-cafe-bestellen", priority: 2 },
        { id: "c-uma-agua-por-favor", type: "chunk", portuguese: "Uma água, por favor.", dutch: "Een water, alstublieft.", dayIntroduced: 4, category: "in-een-cafe-bestellen", priority: 2 },
        { id: "c-com-leite-por-favor", type: "chunk", portuguese: "Com leite, por favor.", dutch: "Met melk, alstublieft.", dayIntroduced: 4, category: "in-een-cafe-bestellen", priority: 2 },
        { id: "c-sem-acucar", type: "chunk", portuguese: "Sem açúcar.", dutch: "Zonder suiker.", dayIntroduced: 4, category: "in-een-cafe-bestellen", priority: 2 },
        { id: "c-mais-alguma-coisa", type: "chunk", portuguese: "Mais alguma coisa?", dutch: "Nog iets?", dayIntroduced: 4, category: "in-een-cafe-bestellen", priority: 2 },
      ],
    },
    {
      id: "d04-grammar",
      lessonDay: 4,
      type: "grammar",
      estimatedMinutes: 5,
      items: [],
      notes: [
        {
          title: "Grammatica",
          body: ["Leer queria eerst als vaste beleefde chunk: “ik zou graag…”."],
          points: [],
        },
      ],
    },
    {
      id: "d04-speaking",
      lessonDay: 4,
      type: "speaking",
      estimatedMinutes: 15,
      items: [
        { id: "c-queria-um-cafe-por-favor", type: "chunk", portuguese: "Queria um café, por favor.", dutch: "Ik zou graag een koffie willen.", dayIntroduced: 4, category: "in-een-cafe-bestellen", priority: 2 },
        { id: "c-queria-uma-cerveja", type: "chunk", portuguese: "Queria uma cerveja.", dutch: "Ik zou graag een bier willen.", dayIntroduced: 4, category: "in-een-cafe-bestellen", priority: 2 },
        { id: "c-uma-agua-por-favor", type: "chunk", portuguese: "Uma água, por favor.", dutch: "Een water, alstublieft.", dayIntroduced: 4, category: "in-een-cafe-bestellen", priority: 2 },
        { id: "c-com-leite-por-favor", type: "chunk", portuguese: "Com leite, por favor.", dutch: "Met melk, alstublieft.", dayIntroduced: 4, category: "in-een-cafe-bestellen", priority: 2 },
        { id: "c-sem-acucar", type: "chunk", portuguese: "Sem açúcar.", dutch: "Zonder suiker.", dayIntroduced: 4, category: "in-een-cafe-bestellen", priority: 2 },
      ],
      tasks: [
        {
          title: "Spreekopdracht",
          kind: "speaking",
          body: ["Bestel een drankje, reageer op “Mais alguma coisa?” en sluit beleefd af."],
          steps: [],
        },
      ],
    },
    {
      id: "d04-test",
      lessonDay: 4,
      type: "test",
      estimatedMinutes: 5,
      items: [
        { id: "c-queria-um-cafe-por-favor", type: "chunk", portuguese: "Queria um café, por favor.", dutch: "Ik zou graag een koffie willen.", dayIntroduced: 4, category: "in-een-cafe-bestellen", priority: 2 },
        { id: "c-queria-uma-cerveja", type: "chunk", portuguese: "Queria uma cerveja.", dutch: "Ik zou graag een bier willen.", dayIntroduced: 4, category: "in-een-cafe-bestellen", priority: 2 },
        { id: "c-uma-agua-por-favor", type: "chunk", portuguese: "Uma água, por favor.", dutch: "Een water, alstublieft.", dayIntroduced: 4, category: "in-een-cafe-bestellen", priority: 2 },
        { id: "c-com-leite-por-favor", type: "chunk", portuguese: "Com leite, por favor.", dutch: "Met melk, alstublieft.", dayIntroduced: 4, category: "in-een-cafe-bestellen", priority: 2 },
        { id: "c-sem-acucar", type: "chunk", portuguese: "Sem açúcar.", dutch: "Zonder suiker.", dayIntroduced: 4, category: "in-een-cafe-bestellen", priority: 2 },
        { id: "w-cafe", type: "word", portuguese: "café", dutch: "koffie", dayIntroduced: 4, category: "in-een-cafe-bestellen", priority: 1 },
        { id: "w-agua", type: "word", portuguese: "água", dutch: "water", dayIntroduced: 4, category: "in-een-cafe-bestellen", priority: 1 },
        { id: "w-cerveja", type: "word", portuguese: "cerveja", dutch: "bier", dayIntroduced: 4, category: "in-een-cafe-bestellen", priority: 1 },
        { id: "w-vinho", type: "word", portuguese: "vinho", dutch: "wijn", dayIntroduced: 4, category: "in-een-cafe-bestellen", priority: 1 },
        { id: "w-cha", type: "word", portuguese: "chá", dutch: "thee", dayIntroduced: 4, category: "in-een-cafe-bestellen", priority: 1 },
      ],
    },
  ],
};
