// Generated by scripts/build-content.mjs — do not edit by hand.
// Source: content/lessons/*.md

import type { LessonDay } from '@/types';

export const day12: LessonDay = {
  day: 12,
  title: "Winkelen",
  goal: "iets zoeken, passen, beoordelen en kopen.",
  checkpoint: false,
  modules: [
    {
      id: "d12-vocabulary",
      lessonDay: 12,
      type: "vocabulary",
      estimatedMinutes: 8,
      items: [
        { id: "w-loja", type: "word", portuguese: "loja", dutch: "winkel", dayIntroduced: 12, category: "winkelen", priority: 1 },
        { id: "w-tamanho", type: "word", portuguese: "tamanho", dutch: "maat", dayIntroduced: 12, category: "winkelen", priority: 1 },
        { id: "w-cor", type: "word", portuguese: "cor", dutch: "kleur", dayIntroduced: 12, category: "winkelen", priority: 1 },
        { id: "w-preco", type: "word", portuguese: "preço", dutch: "prijs", dayIntroduced: 12, category: "winkelen", priority: 1 },
        { id: "w-caro", type: "word", portuguese: "caro", dutch: "duur", dayIntroduced: 12, category: "winkelen", priority: 1 },
        { id: "w-barato", type: "word", portuguese: "barato", dutch: "goedkoop", dayIntroduced: 12, category: "winkelen", priority: 1 },
        { id: "w-grande", type: "word", portuguese: "grande", dutch: "groot", dayIntroduced: 12, category: "winkelen", priority: 1 },
        { id: "w-pequeno", type: "word", portuguese: "pequeno", dutch: "klein", dayIntroduced: 12, category: "winkelen", priority: 1 },
        { id: "w-experimentar", type: "word", portuguese: "experimentar", dutch: "proberen / passen", dayIntroduced: 12, category: "winkelen", priority: 1 },
        { id: "w-procurar", type: "word", portuguese: "procurar", dutch: "zoeken", dayIntroduced: 12, category: "winkelen", priority: 1 },
        { id: "w-comprar", type: "word", portuguese: "comprar", dutch: "kopen", dayIntroduced: 12, category: "winkelen", priority: 1 },
        { id: "w-caixa", type: "word", portuguese: "caixa", dutch: "kassa", dayIntroduced: 12, category: "winkelen", priority: 1 },
        { id: "w-este-esta", type: "word", portuguese: "este / esta", dutch: "deze / dit", dayIntroduced: 12, category: "winkelen", priority: 1 },
        { id: "w-outro-outra", type: "word", portuguese: "outro / outra", dutch: "andere", dayIntroduced: 12, category: "winkelen", priority: 1 },
        { id: "w-ter", type: "word", portuguese: "ter", dutch: "hebben", dayIntroduced: 2, category: "persoonlijke-informatie", priority: 1 },
      ],
    },
    {
      id: "d12-chunks",
      lessonDay: 12,
      type: "chunks",
      estimatedMinutes: 7,
      items: [
        { id: "c-estou-a-procura-de", type: "chunk", portuguese: "Estou à procura de…", dutch: "Ik ben op zoek naar…", dayIntroduced: 12, category: "winkelen", priority: 2 },
        { id: "c-quanto-custa-isto", type: "chunk", portuguese: "Quanto custa isto?", dutch: "Hoeveel kost dit?", dayIntroduced: 12, category: "winkelen", priority: 2 },
        { id: "c-tem-isto-noutro-tamanho", type: "chunk", portuguese: "Tem isto noutro tamanho?", dutch: "Heeft u dit in een andere maat?", dayIntroduced: 12, category: "winkelen", priority: 2 },
        { id: "c-tem-isto-em-preto", type: "chunk", portuguese: "Tem isto em preto?", dutch: "Heeft u dit in het zwart?", dayIntroduced: 12, category: "winkelen", priority: 2 },
        { id: "c-posso-experimentar", type: "chunk", portuguese: "Posso experimentar?", dutch: "Mag ik het passen?", dayIntroduced: 12, category: "winkelen", priority: 2 },
        { id: "c-e-demasiado-grande", type: "chunk", portuguese: "É demasiado grande.", dutch: "Het is te groot.", dayIntroduced: 12, category: "winkelen", priority: 2 },
        { id: "c-gosto-deste", type: "chunk", portuguese: "Gosto deste.", dutch: "Deze vind ik mooi/leuk.", dayIntroduced: 12, category: "winkelen", priority: 2 },
        { id: "c-vou-levar-este", type: "chunk", portuguese: "Vou levar este.", dutch: "Ik neem deze.", dayIntroduced: 12, category: "winkelen", priority: 2 },
      ],
    },
    {
      id: "d12-grammar",
      lessonDay: 12,
      type: "grammar",
      estimatedMinutes: 5,
      items: [],
      notes: [
        {
          title: "Grammatica",
          body: ["Aanwijzende woorden: este/esta, esse/essa. Eerste herkenning van contracties zoals deste."],
          points: [],
        },
      ],
    },
    {
      id: "d12-speaking",
      lessonDay: 12,
      type: "speaking",
      estimatedMinutes: 15,
      items: [],
      tasks: [
        {
          title: "Spreekopdracht",
          kind: "speaking",
          body: ["Koop een kledingstuk: zoek, vraag maat/kleur, pas en beslis."],
          steps: [],
        },
      ],
    },
  ],
};
