// Generated by scripts/build-content.mjs — do not edit by hand.
// Source: content/lessons/*.md

import type { LessonDay } from '@/types';

export const day22: LessonDay = {
  day: 22,
  title: "Eten, wijn & Portugese cultuur",
  goal: "sociaal over eten, wijn en lokale specialiteiten praten.",
  checkpoint: false,
  modules: [
    {
      id: "d22-vocabulary",
      lessonDay: 22,
      type: "vocabulary",
      estimatedMinutes: 8,
      items: [
        { id: "w-vinho-branco", type: "word", portuguese: "vinho branco", dutch: "witte wijn", dayIntroduced: 22, category: "eten-wijn-portugese-cultuur", priority: 1 },
        { id: "w-vinho-tinto", type: "word", portuguese: "vinho tinto", dutch: "rode wijn", dayIntroduced: 22, category: "eten-wijn-portugese-cultuur", priority: 1 },
        { id: "w-queijo", type: "word", portuguese: "queijo", dutch: "kaas", dayIntroduced: 22, category: "eten-wijn-portugese-cultuur", priority: 1 },
        { id: "w-peixe", type: "word", portuguese: "peixe", dutch: "vis", dayIntroduced: 11, category: "in-een-restaurant", priority: 1 },
        { id: "w-marisco", type: "word", portuguese: "marisco", dutch: "zeevruchten", dayIntroduced: 22, category: "eten-wijn-portugese-cultuur", priority: 1 },
        { id: "w-carne", type: "word", portuguese: "carne", dutch: "vlees", dayIntroduced: 11, category: "in-een-restaurant", priority: 1 },
        { id: "w-doce", type: "word", portuguese: "doce", dutch: "zoet", dayIntroduced: 22, category: "eten-wijn-portugese-cultuur", priority: 1 },
        { id: "w-salgado", type: "word", portuguese: "salgado", dutch: "zout / hartig", dayIntroduced: 22, category: "eten-wijn-portugese-cultuur", priority: 1 },
        { id: "w-sabor", type: "word", portuguese: "sabor", dutch: "smaak", dayIntroduced: 22, category: "eten-wijn-portugese-cultuur", priority: 1 },
        { id: "w-tipico", type: "word", portuguese: "típico", dutch: "typisch", dayIntroduced: 22, category: "eten-wijn-portugese-cultuur", priority: 1 },
        { id: "w-delicioso", type: "word", portuguese: "delicioso", dutch: "heerlijk", dayIntroduced: 22, category: "eten-wijn-portugese-cultuur", priority: 1 },
        { id: "w-especialidade", type: "word", portuguese: "especialidade", dutch: "specialiteit", dayIntroduced: 22, category: "eten-wijn-portugese-cultuur", priority: 1 },
        { id: "w-provar", type: "word", portuguese: "provar", dutch: "proeven", dayIntroduced: 22, category: "eten-wijn-portugese-cultuur", priority: 1 },
        { id: "w-preferir", type: "word", portuguese: "preferir", dutch: "verkiezen", dayIntroduced: 10, category: "meningen-voorkeuren", priority: 1 },
        { id: "w-regiao", type: "word", portuguese: "região", dutch: "regio", dayIntroduced: 22, category: "eten-wijn-portugese-cultuur", priority: 1 },
      ],
    },
    {
      id: "d22-chunks",
      lessonDay: 22,
      type: "chunks",
      estimatedMinutes: 7,
      items: [
        { id: "c-gosto-muito-de-comida-portuguesa", type: "chunk", portuguese: "Gosto muito de comida portuguesa.", dutch: "Ik hou erg van Portugees eten.", dayIntroduced: 22, category: "eten-wijn-portugese-cultuur", priority: 2 },
        { id: "c-qual-e-a-especialidade-daqui", type: "chunk", portuguese: "Qual é a especialidade daqui?", dutch: "Wat is de specialiteit hier?", dayIntroduced: 22, category: "eten-wijn-portugese-cultuur", priority: 2 },
        { id: "c-queria-provar-algo-tipico", type: "chunk", portuguese: "Queria provar algo típico.", dutch: "Ik zou iets typisch willen proberen.", dayIntroduced: 22, category: "eten-wijn-portugese-cultuur", priority: 2 },
        { id: "c-prefiro-vinho-branco", type: "chunk", portuguese: "Prefiro vinho branco.", dutch: "Ik heb liever witte wijn.", dayIntroduced: 22, category: "eten-wijn-portugese-cultuur", priority: 2 },
        { id: "c-este-vinho-e-muito-bom", type: "chunk", portuguese: "Este vinho é muito bom.", dutch: "Deze wijn is erg goed.", dayIntroduced: 22, category: "eten-wijn-portugese-cultuur", priority: 2 },
        { id: "c-gosto-mais-de-peixe-do-que-de-carne", type: "chunk", portuguese: "Gosto mais de peixe do que de carne.", dutch: "Ik hou meer van vis dan van vlees.", dayIntroduced: 22, category: "eten-wijn-portugese-cultuur", priority: 2 },
        { id: "c-nunca-provei-isto", type: "chunk", portuguese: "Nunca provei isto.", dutch: "Ik heb dit nog nooit geprobeerd.", dayIntroduced: 22, category: "eten-wijn-portugese-cultuur", priority: 2 },
        { id: "c-o-que-recomenda", type: "chunk", portuguese: "O que recomenda?", dutch: "Wat raadt u aan?", dayIntroduced: 11, category: "in-een-restaurant", priority: 2 },
      ],
    },
    {
      id: "d22-grammar",
      lessonDay: 22,
      type: "grammar",
      estimatedMinutes: 5,
      items: [],
      notes: [
        {
          title: "Grammatica",
          body: ["Vergelijk voorkeuren met gosto mais de X do que de Y."],
          points: [],
        },
      ],
    },
    {
      id: "d22-speaking",
      lessonDay: 22,
      type: "speaking",
      estimatedMinutes: 15,
      items: [],
      tasks: [
        {
          title: "Spreekopdracht",
          kind: "speaking",
          body: ["Bespreek je voorkeuren voor eten en wijn en vraag naar een lokale specialiteit."],
          steps: [],
        },
      ],
    },
  ],
};
