// Generated by scripts/build-content.mjs — do not edit by hand.
// Source: content/lessons/*.md

import type { LessonDay } from '@/types';

export const day21: LessonDay = {
  day: 21,
  title: "Iemand leren kennen",
  goal: "een gesprek niet alleen beantwoorden, maar zelf voortzetten.",
  checkpoint: false,
  modules: [
    {
      id: "d21-vocabulary",
      lessonDay: 21,
      type: "vocabulary",
      estimatedMinutes: 8,
      items: [
        { id: "w-conhecer", type: "word", portuguese: "conhecer", dutch: "leren kennen", dayIntroduced: 17, category: "een-reis-navertellen", priority: 1 },
        { id: "w-pessoa", type: "word", portuguese: "pessoa", dutch: "persoon", dayIntroduced: 21, category: "iemand-leren-kennen", priority: 1 },
        { id: "w-primeira-vez", type: "word", portuguese: "primeira vez", dutch: "eerste keer", dayIntroduced: 21, category: "iemand-leren-kennen", priority: 1 },
        { id: "w-aqui", type: "word", portuguese: "aqui", dutch: "hier", dayIntroduced: 13, category: "de-weg-vragen", priority: 1 },
        { id: "w-local", type: "word", portuguese: "local", dutch: "lokaal", dayIntroduced: 21, category: "iemand-leren-kennen", priority: 1 },
        { id: "w-estrangeiro", type: "word", portuguese: "estrangeiro", dutch: "buitenlander", dayIntroduced: 21, category: "iemand-leren-kennen", priority: 1 },
        { id: "w-sozinho", type: "word", portuguese: "sozinho", dutch: "alleen", dayIntroduced: 21, category: "iemand-leren-kennen", priority: 1 },
        { id: "w-ferias", type: "word", portuguese: "férias", dutch: "vakantie", dayIntroduced: 17, category: "een-reis-navertellen", priority: 1 },
        { id: "w-trabalho", type: "word", portuguese: "trabalho", dutch: "werk", dayIntroduced: 7, category: "werk-beroep", priority: 1 },
        { id: "w-conversa", type: "word", portuguese: "conversa", dutch: "gesprek", dayIntroduced: 21, category: "iemand-leren-kennen", priority: 1 },
        { id: "w-pergunta", type: "word", portuguese: "pergunta", dutch: "vraag", dayIntroduced: 21, category: "iemand-leren-kennen", priority: 1 },
        { id: "w-resposta", type: "word", portuguese: "resposta", dutch: "antwoord", dayIntroduced: 21, category: "iemand-leren-kennen", priority: 1 },
        { id: "w-viver", type: "word", portuguese: "viver", dutch: "wonen", dayIntroduced: 2, category: "persoonlijke-informatie", priority: 1 },
        { id: "w-visitar", type: "word", portuguese: "visitar", dutch: "bezoeken", dayIntroduced: 16, category: "wat-deed-je-gisteren", priority: 1 },
        { id: "w-tempo", type: "word", portuguese: "tempo", dutch: "tijd", dayIntroduced: 21, category: "iemand-leren-kennen", priority: 1 },
      ],
    },
    {
      id: "d21-chunks",
      lessonDay: 21,
      type: "chunks",
      estimatedMinutes: 7,
      items: [
        { id: "c-e-a-tua-primeira-vez-em-portugal", type: "chunk", portuguese: "É a tua primeira vez em Portugal?", dutch: "Is het je eerste keer in Portugal?", dayIntroduced: 21, category: "iemand-leren-kennen", priority: 2 },
        { id: "c-ha-quanto-tempo-estas-aqui", type: "chunk", portuguese: "Há quanto tempo estás aqui?", dutch: "Hoe lang ben je hier?", dayIntroduced: 21, category: "iemand-leren-kennen", priority: 2 },
        { id: "c-estas-aqui-de-ferias", type: "chunk", portuguese: "Estás aqui de férias?", dutch: "Ben je hier op vakantie?", dayIntroduced: 21, category: "iemand-leren-kennen", priority: 2 },
        { id: "c-ou-estas-aqui-em-trabalho", type: "chunk", portuguese: "Ou estás aqui em trabalho?", dutch: "Of ben je hier voor werk?", dayIntroduced: 21, category: "iemand-leren-kennen", priority: 2 },
        { id: "c-vieste-sozinho", type: "chunk", portuguese: "Vieste sozinho?", dutch: "Ben je alleen gekomen?", dayIntroduced: 21, category: "iemand-leren-kennen", priority: 2 },
        { id: "c-o-que-estas-a-achar-de-portugal", type: "chunk", portuguese: "O que estás a achar de Portugal?", dutch: "Wat vind je tot nu toe van Portugal?", dayIntroduced: 21, category: "iemand-leren-kennen", priority: 2 },
        { id: "c-ja-conheces-lisboa", type: "chunk", portuguese: "Já conheces Lisboa?", dutch: "Ken je Lissabon al?", dayIntroduced: 21, category: "iemand-leren-kennen", priority: 2 },
        { id: "c-e-tu", type: "chunk", portuguese: "E tu?", dutch: "En jij?", dayIntroduced: 2, category: "persoonlijke-informatie", priority: 2 },
      ],
    },
    {
      id: "d21-speaking",
      lessonDay: 21,
      type: "speaking",
      estimatedMinutes: 15,
      items: [],
      tasks: [
        {
          title: "Spreekopdracht",
          kind: "speaking",
          body: ["Voer een kennismakingsgesprek en stel na elk antwoord minstens één wedervraag."],
          steps: [],
        },
      ],
    },
  ],
};
