// Generated by scripts/build-content.mjs — do not edit by hand.
// Source: content/lessons/*.md

import type { LessonDay } from '@/types';

export const day30: LessonDay = {
  day: 30,
  title: "Eindtoets",
  goal: "meten wat daadwerkelijk actief beschikbaar is.",
  checkpoint: true,
  challengeId: "the-portuguese-challenge",
  modules: [
    {
      id: "d30-grammar",
      lessonDay: 30,
      type: "grammar",
      estimatedMinutes: 5,
      items: [],
      notes: [
        {
          title: "Beoordelingsmodel",
          body: [],
          points: ["Woordenschat — 20%","Chunks / actieve productie — 20%","Luisteren — 20%","Spreken & uitspraak — 15%","Praktijksituaties — 15%","Vrij gesprek — 10%"],
        },
        {
          title: "Mastery-referentie",
          body: [],
          points: ["0 — Nieuw","1 — Herkend","2 — Herinnerd","3 — Geproduceerd","4 — Actief"],
        },
      ],
    },
    {
      id: "d30-test",
      lessonDay: 30,
      type: "test",
      estimatedMinutes: 5,
      items: [],
      tasks: [
        {
          title: "Onderdeel 1 — Actieve woordenschat",
          kind: "test",
          body: ["30 willekeurige items. Nederlands → Portugees produceren, geen multiple choice."],
          steps: [],
        },
        {
          title: "Onderdeel 2 — Chunks",
          kind: "test",
          body: ["20 Nederlandse situaties → passende Portugese zin produceren.","Voorbeeld:"],
          steps: ["Vraag iemand langzamer te praten.","Antwoord: Pode falar mais devagar?"],
        },
        {
          title: "Onderdeel 3 — Luistervaardigheid",
          kind: "test",
          body: ["10–15 gesproken Portugese zinnen begrijpen en de betekenis weergeven."],
          steps: [],
        },
        {
          title: "Onderdeel 4 — Uitspraak",
          kind: "test",
          body: ["10 kernzinnen hardop uitspreken. Beoordeling op:","Perfect accent is niet vereist."],
          steps: ["verstaanbaarheid","ritme","Portugese klanken","natuurlijke woordverbindingen"],
        },
        {
          title: "Onderdeel 5 — Praktijkscenario's",
          kind: "test",
          body: ["Vijf willekeurige situaties uit:"],
          steps: ["café","restaurant","winkel","trein","hotel","route vragen","kennismaking","werk","plannen maken","probleem oplossen"],
        },
        {
          title: "Onderdeel 6 — Eindgesprek",
          kind: "test",
          body: ["10–15 minuten volledig Europees Portugees met onverwachte vervolgvragen."],
          steps: [],
        },
      ],
    },
  ],
};
