// Generated by scripts/build-content.mjs — do not edit by hand.
// Source: content/lessons/*.md

import type { LessonDay } from '@/types';

export const day07: LessonDay = {
  day: 7,
  title: "Werk & beroep",
  goal: "vertellen wat je doet en eenvoudige werkvragen begrijpen.",
  checkpoint: false,
  modules: [
    {
      id: "d07-vocabulary",
      lessonDay: 7,
      type: "vocabulary",
      estimatedMinutes: 8,
      items: [
        { id: "w-trabalhar", type: "word", portuguese: "trabalhar", dutch: "werken", dayIntroduced: 7, category: "werk-beroep", priority: 1 },
        { id: "w-trabalho", type: "word", portuguese: "trabalho", dutch: "werk", dayIntroduced: 7, category: "werk-beroep", priority: 1 },
        { id: "w-empresa", type: "word", portuguese: "empresa", dutch: "bedrijf", dayIntroduced: 7, category: "werk-beroep", priority: 1 },
        { id: "w-escritorio", type: "word", portuguese: "escritório", dutch: "kantoor", dayIntroduced: 7, category: "werk-beroep", priority: 1 },
        { id: "w-colega", type: "word", portuguese: "colega", dutch: "collega", dayIntroduced: 7, category: "werk-beroep", priority: 1 },
        { id: "w-cliente", type: "word", portuguese: "cliente", dutch: "klant", dayIntroduced: 7, category: "werk-beroep", priority: 1 },
        { id: "w-reuniao", type: "word", portuguese: "reunião", dutch: "vergadering", dayIntroduced: 7, category: "werk-beroep", priority: 1 },
        { id: "w-projeto", type: "word", portuguese: "projeto", dutch: "project", dayIntroduced: 7, category: "werk-beroep", priority: 1 },
        { id: "w-marketing", type: "word", portuguese: "marketing", dutch: "marketing", dayIntroduced: 7, category: "werk-beroep", priority: 1 },
        { id: "w-publicidade", type: "word", portuguese: "publicidade", dutch: "reclame / advertising", dayIntroduced: 7, category: "werk-beroep", priority: 1 },
        { id: "w-online", type: "word", portuguese: "online", dutch: "online", dayIntroduced: 7, category: "werk-beroep", priority: 1 },
        { id: "w-vender", type: "word", portuguese: "vender", dutch: "verkopen", dayIntroduced: 7, category: "werk-beroep", priority: 1 },
        { id: "w-ajudar", type: "word", portuguese: "ajudar", dutch: "helpen", dayIntroduced: 7, category: "werk-beroep", priority: 1 },
        { id: "w-fazer", type: "word", portuguese: "fazer", dutch: "doen / maken", dayIntroduced: 7, category: "werk-beroep", priority: 1 },
        { id: "w-gostar", type: "word", portuguese: "gostar", dutch: "leuk vinden", dayIntroduced: 7, category: "werk-beroep", priority: 1 },
      ],
    },
    {
      id: "d07-chunks",
      lessonDay: 7,
      type: "chunks",
      estimatedMinutes: 7,
      items: [
        { id: "c-o-que-fazes", type: "chunk", portuguese: "O que fazes?", dutch: "Wat doe je voor werk?", dayIntroduced: 7, category: "werk-beroep", priority: 2 },
        { id: "c-trabalho-em-marketing", type: "chunk", portuguese: "Trabalho em marketing.", dutch: "Ik werk in marketing.", dayIntroduced: 7, category: "werk-beroep", priority: 2 },
        { id: "c-trabalho-numa-empresa", type: "chunk", portuguese: "Trabalho numa empresa.", dutch: "Ik werk bij een bedrijf.", dayIntroduced: 7, category: "werk-beroep", priority: 2 },
        { id: "c-trabalho-com-clientes", type: "chunk", portuguese: "Trabalho com clientes.", dutch: "Ik werk met klanten.", dayIntroduced: 7, category: "werk-beroep", priority: 2 },
        { id: "c-tenho-uma-reuniao-hoje", type: "chunk", portuguese: "Tenho uma reunião hoje.", dutch: "Ik heb vandaag een vergadering.", dayIntroduced: 7, category: "werk-beroep", priority: 2 },
        { id: "c-estou-a-trabalhar-num-projeto", type: "chunk", portuguese: "Estou a trabalhar num projeto.", dutch: "Ik werk aan een project.", dayIntroduced: 7, category: "werk-beroep", priority: 2 },
        { id: "c-gosto-do-meu-trabalho", type: "chunk", portuguese: "Gosto do meu trabalho.", dutch: "Ik vind mijn werk leuk.", dayIntroduced: 7, category: "werk-beroep", priority: 2 },
        { id: "c-e-tu-o-que-fazes", type: "chunk", portuguese: "E tu, o que fazes?", dutch: "En jij, wat doe je?", dayIntroduced: 7, category: "werk-beroep", priority: 2 },
      ],
    },
    {
      id: "d07-grammar",
      lessonDay: 7,
      type: "grammar",
      estimatedMinutes: 5,
      items: [],
      notes: [
        {
          title: "Grammatica",
          body: ["Tegenwoordige tijd van regelmatige -ar-werkwoorden; focus op eu/tu/nós.","Europees Portugees gebruikt bijvoorbeeld:"],
          points: ["Estou a trabalhar."],
        },
      ],
    },
    {
      id: "d07-speaking",
      lessonDay: 7,
      type: "speaking",
      estimatedMinutes: 15,
      items: [],
      tasks: [
        {
          title: "Spreekopdracht",
          kind: "speaking",
          body: ["Beantwoord vier werkvragen en praat 45–60 seconden over je werk."],
          steps: [],
        },
      ],
    },
  ],
};
