// Generated by scripts/build-content.mjs — do not edit by hand.
// Source: content/lessons/*.md

import type { LessonDay } from '@/types';

export const day19: LessonDay = {
  day: 19,
  title: "Plannen maken met iemand",
  goal: "iemand uitnodigen en samen tijd/plek afspreken.",
  checkpoint: false,
  modules: [
    {
      id: "d19-vocabulary",
      lessonDay: 19,
      type: "vocabulary",
      estimatedMinutes: 8,
      items: [
        { id: "w-combinar", type: "word", portuguese: "combinar", dutch: "afspreken", dayIntroduced: 19, category: "plannen-maken-met-iemand", priority: 1 },
        { id: "w-encontrar-se", type: "word", portuguese: "encontrar-se", dutch: "afspreken / elkaar ontmoeten", dayIntroduced: 19, category: "plannen-maken-met-iemand", priority: 1 },
        { id: "w-livre", type: "word", portuguese: "livre", dutch: "vrij", dayIntroduced: 19, category: "plannen-maken-met-iemand", priority: 1 },
        { id: "w-ocupado", type: "word", portuguese: "ocupado", dutch: "bezet", dayIntroduced: 3, category: "hoe-gaat-het", priority: 1 },
        { id: "w-talvez", type: "word", portuguese: "talvez", dutch: "misschien", dayIntroduced: 19, category: "plannen-maken-met-iemand", priority: 1 },
        { id: "w-cinema", type: "word", portuguese: "cinema", dutch: "bioscoop", dayIntroduced: 19, category: "plannen-maken-met-iemand", priority: 1 },
        { id: "w-bar", type: "word", portuguese: "bar", dutch: "bar", dayIntroduced: 19, category: "plannen-maken-met-iemand", priority: 1 },
        { id: "w-sabado", type: "word", portuguese: "sábado", dutch: "zaterdag", dayIntroduced: 19, category: "plannen-maken-met-iemand", priority: 1 },
        { id: "w-domingo", type: "word", portuguese: "domingo", dutch: "zondag", dayIntroduced: 19, category: "plannen-maken-met-iemand", priority: 1 },
        { id: "w-hoje", type: "word", portuguese: "hoje", dutch: "vandaag", dayIntroduced: 3, category: "hoe-gaat-het", priority: 1 },
        { id: "w-amanha", type: "word", portuguese: "amanhã", dutch: "morgen", dayIntroduced: 18, category: "morgen-en-de-toekomst", priority: 1 },
        { id: "w-hora", type: "word", portuguese: "hora", dutch: "tijd / uur", dayIntroduced: 5, category: "getallen-geld-tijd", priority: 1 },
        { id: "w-lugar", type: "word", portuguese: "lugar", dutch: "plaats", dayIntroduced: 19, category: "plannen-maken-met-iemand", priority: 1 },
        { id: "w-poder", type: "word", portuguese: "poder", dutch: "kunnen", dayIntroduced: 19, category: "plannen-maken-met-iemand", priority: 1 },
        { id: "w-querer", type: "word", portuguese: "querer", dutch: "willen", dayIntroduced: 4, category: "in-een-cafe-bestellen", priority: 1 },
      ],
    },
    {
      id: "d19-chunks",
      lessonDay: 19,
      type: "chunks",
      estimatedMinutes: 7,
      items: [
        { id: "c-queres-tomar-um-cafe", type: "chunk", portuguese: "Queres tomar um café?", dutch: "Wil je koffie drinken?", dayIntroduced: 19, category: "plannen-maken-met-iemand", priority: 2 },
        { id: "c-queres-jantar-comigo", type: "chunk", portuguese: "Queres jantar comigo?", dutch: "Wil je met mij eten?", dayIntroduced: 19, category: "plannen-maken-met-iemand", priority: 2 },
        { id: "c-podemos-ir-amanha", type: "chunk", portuguese: "Podemos ir amanhã.", dutch: "We kunnen morgen gaan.", dayIntroduced: 19, category: "plannen-maken-met-iemand", priority: 2 },
        { id: "c-vamos-ao-centro", type: "chunk", portuguese: "Vamos ao centro?", dutch: "Zullen we naar het centrum gaan?", dayIntroduced: 19, category: "plannen-maken-met-iemand", priority: 2 },
        { id: "c-a-que-horas", type: "chunk", portuguese: "A que horas?", dutch: "Hoe laat?", dayIntroduced: 19, category: "plannen-maken-met-iemand", priority: 2 },
        { id: "c-onde-nos-encontramos", type: "chunk", portuguese: "Onde nos encontramos?", dutch: "Waar spreken we af?", dayIntroduced: 19, category: "plannen-maken-met-iemand", priority: 2 },
        { id: "c-as-oito-esta-bem", type: "chunk", portuguese: "Às oito está bem?", dutch: "Is acht uur goed?", dayIntroduced: 19, category: "plannen-maken-met-iemand", priority: 2 },
        { id: "c-combinado", type: "chunk", portuguese: "Combinado!", dutch: "Afgesproken!", dayIntroduced: 19, category: "plannen-maken-met-iemand", priority: 2 },
      ],
    },
    {
      id: "d19-speaking",
      lessonDay: 19,
      type: "speaking",
      estimatedMinutes: 15,
      items: [],
      tasks: [
        {
          title: "Spreekopdracht",
          kind: "speaking",
          body: ["Maak een plan waarbij je ook een voorgesteld tijdstip afwijst en een alternatief afspreekt."],
          steps: [],
        },
      ],
    },
  ],
};
