// Generated by scripts/build-content.mjs — do not edit by hand.

import type { LessonDay } from '@/types';
import { day01 } from './day-01';
import { day02 } from './day-02';
import { day03 } from './day-03';
import { day04 } from './day-04';
import { day05 } from './day-05';
import { day06 } from './day-06';
import { day07 } from './day-07';
import { day08 } from './day-08';
import { day09 } from './day-09';
import { day10 } from './day-10';
import { day11 } from './day-11';
import { day12 } from './day-12';
import { day13 } from './day-13';
import { day14 } from './day-14';
import { day15 } from './day-15';
import { day16 } from './day-16';
import { day17 } from './day-17';
import { day18 } from './day-18';
import { day19 } from './day-19';
import { day20 } from './day-20';
import { day21 } from './day-21';
import { day22 } from './day-22';
import { day23 } from './day-23';
import { day24 } from './day-24';
import { day25 } from './day-25';
import { day26 } from './day-26';
import { day27 } from './day-27';
import { day28 } from './day-28';
import { day29 } from './day-29';
import { day30 } from './day-30';

/** All 30 curriculum days, in order. */
export const days: LessonDay[] = [day01, day02, day03, day04, day05, day06, day07, day08, day09, day10, day11, day12, day13, day14, day15, day16, day17, day18, day19, day20, day21, day22, day23, day24, day25, day26, day27, day28, day29, day30];
