#!/usr/bin/env node
import { createHash } from 'node:crypto';
import { readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';

/**
 * Generates the service worker after a build.
 *
 * Vite hashes asset filenames, so the precache list can only be known once the
 * build exists. This walks dist/ and writes the list into sw.js together with a
 * cache name derived from the file contents, so a new build replaces the old
 * cache instead of serving stale assets.
 */

const DIST = 'dist';

/** Files that never belong in the precache. */
const SKIP = new Set(['sw.js', '.vite']);

function walk(dir) {
  const entries = [];
  for (const name of readdirSync(dir)) {
    if (SKIP.has(name)) continue;
    const full = join(dir, name);
    if (statSync(full).isDirectory()) entries.push(...walk(full));
    else entries.push(full);
  }
  return entries;
}

const files = walk(DIST);
const assets = files
  .map((file) => '/' + relative(DIST, file).split('\\').join('/'))
  .sort();

const hash = createHash('sha256');
for (const file of files.sort()) {
  hash.update(readFileSync(file));
}
const version = hash.digest('hex').slice(0, 12);

const sw = `// Generated by scripts/build-sw.mjs — do not edit by hand.
const CACHE = 'polyyaps-${version}';
const PRECACHE = ${JSON.stringify(assets, null, 2)};

// Lesson audio is fetched on demand and kept after first use, so the first
// install stays small — the strategy from architecture section 20.
const RUNTIME = 'polyyaps-runtime';

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)).then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(
          keys
            .filter((key) => key !== CACHE && key !== RUNTIME)
            .map((key) => caches.delete(key)),
        ),
      )
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  // Every in-app route resolves to the same document, so a deep link opened
  // offline still starts the app.
  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request).catch(() =>
        caches.match('/index.html').then((cached) => cached ?? Response.error()),
      ),
    );
    return;
  }

  if (url.pathname.startsWith('/audio/')) {
    event.respondWith(
      caches.match(request).then(
        (cached) =>
          cached ??
          fetch(request).then((response) => {
            const copy = response.clone();
            void caches.open(RUNTIME).then((cache) => cache.put(request, copy));
            return response;
          }),
      ),
    );
    return;
  }

  event.respondWith(
    caches.match(request).then((cached) => cached ?? fetch(request)),
  );
});
`;

writeFileSync(join(DIST, 'sw.js'), sw);
console.log(`Generated dist/sw.js precaching ${assets.length} files (cache polyyaps-${version})`);
