#!/usr/bin/env node
import { mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { parseLessons, slug } from './lib/parse-lessons.mjs';

/**
 * Generates typed course data from the editorial Markdown.
 *
 *   content/lessons/*.md  ->  src/content/pt-PT/days/day-NN.ts
 *
 * Run with `npm run build:content`. The generated files are committed so the
 * app never parses Markdown at runtime or build time.
 */

const OUT_DIR = 'src/content/pt-PT/days';

/** Checkpoint days and their boss challenge — masterplan step 5. */
const CHALLENGES = {
  5: 'cafe-challenge',
  10: 'meet-a-local',
  15: 'travel-day',
  20: 'ontem-hoje-amanha',
  25: 'night-out',
  30: 'the-portuguese-challenge',
};

/** Chunks outrank single words: they are usable in conversation immediately. */
const PRIORITY = { word: 1, chunk: 2 };

/** Indicative module durations — masterplan step 4, "Vast lesuur". */
const MODULE_MINUTES = {
  vocabulary: 8,
  chunks: 7,
  listening: 10,
  grammar: 5,
  speaking: 15,
  test: 5,
};

function quote(value) {
  return JSON.stringify(value);
}

function buildItems(day, firstSeen) {
  const items = [];
  const onThisDay = new Set();

  for (const raw of day.items) {
    const prefix = raw.type === 'word' ? 'w' : 'c';
    const id = `${prefix}-${slug(raw.portuguese)}`;

    // The same item listed twice within one day is an editorial slip.
    if (onThisDay.has(id)) continue;
    onThisDay.add(id);

    // An item that reappears on a later day stays part of that day's material,
    // but keeps its original dayIntroduced so the review engine treats it as
    // one learning item rather than a second entry.
    if (!firstSeen.has(id)) {
      firstSeen.set(id, { day: day.day, category: slug(day.title) });
    }
    const origin = firstSeen.get(id);

    items.push({
      id,
      type: raw.type,
      portuguese: raw.portuguese,
      dutch: raw.dutch,
      dayIntroduced: origin.day,
      category: origin.category,
      priority: PRIORITY[raw.type],
    });
  }

  return items;
}

function buildModules(day, items) {
  const modules = [];
  const add = (type, extra) => {
    modules.push({
      id: `d${String(day.day).padStart(2, '0')}-${type}`,
      lessonDay: day.day,
      type,
      estimatedMinutes: MODULE_MINUTES[type],
      items: [],
      ...extra,
    });
  };

  const words = items.filter((item) => item.type === 'word');
  const chunks = items.filter((item) => item.type === 'chunk');
  const grammarNotes = day.notes.filter((note) => note.noteType === 'grammar');
  const listeningNotes = day.notes.filter((note) => note.noteType === 'listening');
  const speakingTasks = day.tasks.filter((task) => task.taskType !== 'test');
  const testTasks = day.tasks.filter((task) => task.taskType === 'test');

  // Canonical order from the architecture, minus modules the engines own:
  // `review` is generated by the review engine (V0.4), not by content.
  if (words.length) add('vocabulary', { items: words });
  if (chunks.length) add('chunks', { items: chunks });
  if (listeningNotes.length) add('listening', { notes: listeningNotes });
  if (grammarNotes.length) add('grammar', { notes: grammarNotes });
  if (speakingTasks.length) add('speaking', { tasks: speakingTasks });
  if (testTasks.length) add('test', { tasks: testTasks });

  return modules;
}

function renderDay(day, items, modules) {
  const challengeId = CHALLENGES[day.day];

  const lines = [
    '// Generated by scripts/build-content.mjs — do not edit by hand.',
    '// Source: content/lessons/*.md',
    '',
    "import type { LessonDay } from '@/types';",
    '',
    `export const day${String(day.day).padStart(2, '0')}: LessonDay = {`,
    `  day: ${day.day},`,
    `  title: ${quote(day.title)},`,
    `  goal: ${quote(day.goal)},`,
    `  checkpoint: ${Boolean(challengeId)},`,
  ];

  if (challengeId) lines.push(`  challengeId: ${quote(challengeId)},`);

  lines.push('  modules: [');
  for (const module of modules) {
    lines.push('    {');
    lines.push(`      id: ${quote(module.id)},`);
    lines.push(`      lessonDay: ${module.lessonDay},`);
    lines.push(`      type: ${quote(module.type)},`);
    lines.push(`      estimatedMinutes: ${module.estimatedMinutes},`);

    if (module.items.length) {
      lines.push('      items: [');
      for (const item of module.items) {
        lines.push(
          `        { id: ${quote(item.id)}, type: ${quote(item.type)}, ` +
            `portuguese: ${quote(item.portuguese)}, dutch: ${quote(item.dutch)}, ` +
            `dayIntroduced: ${item.dayIntroduced}, category: ${quote(item.category)}, ` +
            `priority: ${item.priority} },`,
        );
      }
      lines.push('      ],');
    } else {
      lines.push('      items: [],');
    }

    if (module.notes) {
      lines.push('      notes: [');
      for (const note of module.notes) {
        lines.push('        {');
        lines.push(`          title: ${quote(note.title)},`);
        lines.push(`          body: ${JSON.stringify(note.body)},`);
        lines.push(`          points: ${JSON.stringify(note.points)},`);
        lines.push('        },');
      }
      lines.push('      ],');
    }

    if (module.tasks) {
      lines.push('      tasks: [');
      for (const task of module.tasks) {
        lines.push('        {');
        lines.push(`          title: ${quote(task.title)},`);
        lines.push(`          kind: ${quote(task.taskType)},`);
        lines.push(`          body: ${JSON.stringify(task.body)},`);
        lines.push(`          steps: ${JSON.stringify(task.steps)},`);
        lines.push('        },');
      }
      lines.push('      ],');
    }

    lines.push('    },');
  }
  lines.push('  ],');
  lines.push('};');
  lines.push('');

  void items;
  return lines.join('\n');
}

function renderIndex(days) {
  const names = days.map((day) => `day${String(day.day).padStart(2, '0')}`);
  return [
    '// Generated by scripts/build-content.mjs — do not edit by hand.',
    '',
    "import type { LessonDay } from '@/types';",
    ...days.map(
      (day, index) =>
        `import { ${names[index]} } from './day-${String(day.day).padStart(2, '0')}';`,
    ),
    '',
    '/** All 30 curriculum days, in order. */',
    `export const days: LessonDay[] = [${names.join(', ')}];`,
    '',
  ].join('\n');
}

/**
 * Builds the generated files in memory.
 * Returns { files: Map<filename, contents>, days, itemCount } so the validator
 * can compare against what is committed without writing anything.
 */
export function generate() {
  const parsed = parseLessons();
  const files = new Map();
  const firstSeen = new Map();
  const built = [];
  let itemCount = 0;

  for (const day of parsed) {
    const items = buildItems(day, firstSeen);
    const modules = buildModules(day, items);
    itemCount += items.filter((item) => item.dayIntroduced === day.day).length;
    built.push({ ...day, generatedItems: items, generatedModules: modules });
    files.set(`day-${String(day.day).padStart(2, '0')}.ts`, renderDay(day, items, modules));
  }

  files.set('index.ts', renderIndex(parsed));
  return { files, days: built, itemCount, outDir: OUT_DIR };
}

function writeAll() {
  const { files, days, itemCount } = generate();

  rmSync(OUT_DIR, { recursive: true, force: true });
  mkdirSync(OUT_DIR, { recursive: true });
  for (const [name, contents] of files) {
    writeFileSync(join(OUT_DIR, name), contents);
  }

  console.log(
    `Generated ${days.length} days with ${itemCount} unique learning items into ${OUT_DIR}`,
  );
}

// Only write when run directly, so importing this module stays side-effect free.
if (process.argv[1] && process.argv[1].endsWith('build-content.mjs')) {
  writeAll();
}
